/**
 * Build `fixtures/resolution-vectors.json`.
 *
 * ## The expectations do not come from the implementation
 *
 * A golden-vector file generated by running the code it tests proves that the
 * code does what it does. This repository has a precedent for the honest
 * version: `packages/marc`'s corpus is emitted by a byte-level writer that
 * shares no code with the codec, and a test asserts that import list, which is
 * what makes "two independent implementations agree" evidence.
 *
 * The same trick, twice:
 *
 *   RANK      the expected `specificity` is computed with BIT SHIFTS here, and
 *             with a table of named weights in `rank.ts`. Both are checked
 *             against real PostgreSQL 16 in the phase-12 divergence entry.
 *
 *   TIME      the expected instants come from `slowCandidates`, a LINEAR SCAN
 *             over a four-day window in one-minute steps that formats every
 *             candidate and keeps the ones that match. It is thousands of times
 *             slower than the ±24-hour probe in `calendar.ts` and it is
 *             obviously correct, which is the whole point — it cannot lose an
 *             ambiguous instant because it never guesses which offsets to try.
 *
 *   DUE DATE  civil-date arithmetic is done by stepping one day at a time and
 *             reading each result back out of `Intl`, rather than by the
 *             `daysFromCivil` day-number arithmetic the package uses.
 *
 * Run with `pnpm --filter @libriant/circ-policy vectors:build`. The output is
 * COMMITTED and reviewed; this script exists so that a change to it is visible
 * in a diff rather than being folklore.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { greekCalendarExceptions } from '../src/greek-calendar.js';
import type { CivilDateTime } from '../src/types.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, '..', 'fixtures', 'resolution-vectors.json');

const TZ = 'Europe/Athens';
const SELECTORS = [
  'patronCategoryId',
  'itemTypeId',
  'owningBranchId',
  'shelvingLocationId',
  'checkoutBranchId',
  'pickupBranchId',
] as const;

// ---------------------------------------------------------------------------
// The slow, obvious reference. Nothing here imports from src/calendar.ts.
// ---------------------------------------------------------------------------

const fmtCache = new Map<string, Intl.DateTimeFormat>();
const fmt = (tz: string) => {
  let f = fmtCache.get(tz);
  if (f === undefined) {
    f = new Intl.DateTimeFormat('en-US', {
      timeZone: tz,
      hourCycle: 'h23',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });
    fmtCache.set(tz, f);
  }
  return f;
};

function slowParts(tz: string, ms: number): CivilDateTime {
  const o: Record<string, string> = {};
  for (const p of fmt(tz).formatToParts(ms)) if (p.type !== 'literal') o[p.type] = p.value;
  return {
    year: Number(o['year']),
    month: Number(o['month']),
    day: Number(o['day']),
    hour: Number(o['hour']) % 24,
    minute: Number(o['minute']),
    second: Number(o['second']),
  };
}

const sameCivil = (a: CivilDateTime, b: CivilDateTime) =>
  a.year === b.year &&
  a.month === b.month &&
  a.day === b.day &&
  a.hour === b.hour &&
  a.minute === b.minute;

/**
 * Every instant whose local time in `tz` is `civil`, found by trying EVERY
 * OFFSET.
 *
 * -14:00 to +14:00 in fifteen-minute steps — 113 candidates — each turned into
 * an instant and formatted back, keeping the ones that match. That is the whole
 * space of UTC offsets the IANA database uses in the modern era, so it cannot
 * miss a candidate; and unlike the ±24-hour probe in `calendar.ts` it makes no
 * assumption about WHICH offsets are plausible, which is exactly the assumption
 * that loses the second instant of an autumn fold.
 *
 * (The first draft scanned four days in one-minute steps. It is even more
 * obviously exhaustive and it took over ten minutes to build the file, which is
 * a reference nobody would run.)
 */
const OFFSET_STEPS = (() => {
  const out: number[] = [];
  for (let m = -14 * 60; m <= 14 * 60; m += 15) out.push(m * 60_000);
  return out;
})();

function slowCandidates(tz: string, civil: CivilDateTime): number[] {
  const wall = Date.UTC(civil.year, civil.month - 1, civil.day, civil.hour, civil.minute, 0);
  const out: number[] = [];
  for (const offset of OFFSET_STEPS) {
    const t = wall - offset;
    if (sameCivil(slowParts(tz, t), civil) && !out.includes(t)) out.push(t);
  }
  return out.sort((a, b) => a - b);
}

/** Civil date + N days, by stepping and re-reading. Never a day number. */
function slowAddDays(tz: string, civil: CivilDateTime, days: number): CivilDateTime {
  let cur = civil;
  const step = days >= 0 ? 1 : -1;
  for (let i = 0; i !== days; i += step) {
    // Noon is safe from every DST transition on earth, so stepping through it
    // cannot skip or repeat a civil date.
    const noon = slowCandidates(tz, { ...cur, hour: 12, minute: 0, second: 0 })[0]!;
    const next = slowParts(tz, noon + step * 86_400_000);
    cur = { ...cur, year: next.year, month: next.month, day: next.day };
  }
  return cur;
}

const iso = (ms: number) => new Date(ms).toISOString();

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/** Mon–Fri 08:00–14:00 + 17:00–21:00, Sat 09:00–13:00, Sun closed. */
const SPLIT_WEEK = [
  { weekday: 0, intervals: [] },
  ...[1, 2, 3, 4, 5].map((weekday) => ({
    weekday,
    intervals: [
      { open: 480, close: 840 },
      { open: 1020, close: 1260 },
    ],
  })),
  { weekday: 6, intervals: [{ open: 540, close: 780 }] },
];

/** Mon–Fri 09:00–17:00, weekend closed. The ordinary Anglophone shape. */
const SIMPLE_WEEK = [
  { weekday: 0, intervals: [] },
  ...[1, 2, 3, 4, 5].map((weekday) => ({ weekday, intervals: [{ open: 540, close: 1020 }] })),
  { weekday: 6, intervals: [] },
];

const AUGUST_CLOSURE = Array.from({ length: 11 }, (_, i) => ({
  date: { year: 2026, month: 8, day: 10 + i },
  intervals: [] as { open: number; close: number }[],
  name: 'Θερινή διακοπή',
}));

const calendars = {
  'cal-athens-split': {
    id: 'cal-athens-split',
    timezone: TZ,
    weekly: SPLIT_WEEK,
    exceptions: [...greekCalendarExceptions(2026), ...AUGUST_CLOSURE],
    definedFrom: { year: 2025, month: 1, day: 1 },
    definedTo: { year: 2027, month: 12, day: 31 },
  },
  'cal-athens-simple': {
    id: 'cal-athens-simple',
    timezone: TZ,
    weekly: SIMPLE_WEEK,
    exceptions: greekCalendarExceptions(2026),
    definedFrom: { year: 2025, month: 1, day: 1 },
    definedTo: { year: 2027, month: 12, day: 31 },
  },
  'cal-always-open': {
    id: 'cal-always-open',
    timezone: TZ,
    weekly: Array.from({ length: 7 }, (_, weekday) => ({
      weekday,
      intervals: [{ open: 0, close: 1440 }],
    })),
    exceptions: [],
    definedFrom: { year: 2025, month: 1, day: 1 },
    definedTo: { year: 2027, month: 12, day: 31 },
  },
};

const baseLoan = {
  loanable: true,
  profile: 'rolling',
  period: { value: 14, unit: 'days' },
  fixedDueDateSetId: null,
  dueTimeOfDay: null,
  closedDayHandling: 'keep',
  openingTimeOffset: null,
  maxPeriod: null,
  renewable: true,
  renewalsAllowed: 2,
  renewalPeriod: null,
  renewFrom: 'currentDueDate',
  noRenewalBefore: null,
  noRenewalBeforeRelativeTo: 'dueDate',
  renewWithOutstandingHolds: true,
  alternateCheckoutPeriodWithHolds: null,
  alternateRenewalPeriodWithHolds: null,
  itemLimitForPolicy: null,
};

const loanPolicies: Record<string, Record<string, unknown>> = {
  'lp-14d': { ...baseLoan, id: 'lp-14d', name: '14 days' },
  'lp-14d-closing': {
    ...baseLoan,
    id: 'lp-14d-closing',
    name: '14 days, due at closing',
    dueTimeOfDay: { hour: 21, minute: 0 },
  },
  'lp-14d-nextopen': {
    ...baseLoan,
    id: 'lp-14d-nextopen',
    name: '14 days, roll to next open',
    closedDayHandling: 'startOfNextOpenDay',
  },
  'lp-14d-endnext': {
    ...baseLoan,
    id: 'lp-14d-endnext',
    name: '14 days, end of next open day',
    closedDayHandling: 'endOfNextOpenDay',
  },
  'lp-14d-prev': {
    ...baseLoan,
    id: 'lp-14d-prev',
    name: '14 days, pull back',
    closedDayHandling: 'endOfPreviousOpenDay',
  },
  'lp-2h': {
    ...baseLoan,
    id: 'lp-2h',
    name: '2 hours',
    period: { value: 2, unit: 'hours' },
    renewable: false,
    renewalsAllowed: 0,
  },
  'lp-2h-inlibrary': {
    ...baseLoan,
    id: 'lp-2h-inlibrary',
    name: '2-hour in-library reserve',
    period: { value: 2, unit: 'hours' },
    closedDayHandling: 'endOfCurrentOpenHours',
    renewable: false,
    renewalsAllowed: 0,
  },
  'lp-3w': { ...baseLoan, id: 'lp-3w', name: '3 weeks', period: { value: 3, unit: 'weeks' } },
  'lp-1m': { ...baseLoan, id: 'lp-1m', name: '1 month', period: { value: 1, unit: 'months' } },
  'lp-90m': {
    ...baseLoan,
    id: 'lp-90m',
    name: '90 minutes',
    period: { value: 90, unit: 'minutes' },
  },
  'lp-indefinite': {
    ...baseLoan,
    id: 'lp-indefinite',
    name: 'Staff',
    profile: 'indefinite',
    period: null,
  },
  'lp-hold-short': {
    ...baseLoan,
    id: 'lp-hold-short',
    name: '14 days, 7 with a hold',
    alternateCheckoutPeriodWithHolds: { value: 7, unit: 'days' },
  },
  'lp-capped': {
    ...baseLoan,
    id: 'lp-capped',
    name: '3 weeks capped at 10 days',
    period: { value: 3, unit: 'weeks' },
    maxPeriod: { value: 10, unit: 'days' },
  },
};

const baseFine = {
  interval: { value: 1, unit: 'days' },
  amountPerInterval: { minorUnits: 20, currency: 'EUR' },
  chargeAt: 'intervalEnd',
  gracePeriod: null,
  graceSuppressesNotice: false,
  countClosedDays: true,
  maximumFine: null,
  minimumFine: null,
  capAtReplacementCost: false,
  forgiveOn: [],
  suspension: null,
};

const finePolicies: Record<string, Record<string, unknown>> = {
  'fp-20c-day': { ...baseFine, id: 'fp-20c-day', name: '20c a day' },
  'fp-grace3': {
    ...baseFine,
    id: 'fp-grace3',
    name: '20c a day, 3 days grace',
    gracePeriod: { value: 3, unit: 'days' },
  },
  'fp-open-only': {
    ...baseFine,
    id: 'fp-open-only',
    name: '20c an open day',
    countClosedDays: false,
  },
  'fp-max-5eur': {
    ...baseFine,
    id: 'fp-max-5eur',
    name: '20c a day, capped at 5 euro',
    maximumFine: { minorUnits: 500, currency: 'EUR' },
  },
  'fp-hourly': {
    ...baseFine,
    id: 'fp-hourly',
    name: '50c an hour',
    interval: { value: 1, unit: 'hours' },
    amountPerInterval: { minorUnits: 50, currency: 'EUR' },
  },
  'fp-start': {
    ...baseFine,
    id: 'fp-start',
    name: '20c a day, charged up front',
    chargeAt: 'intervalStart',
  },
};

/** One snapshot with a rule at every level of the hierarchy. */
const rule = (
  id: string,
  name: string,
  sel: Partial<Record<(typeof SELECTORS)[number], string>>,
  priority = 0,
  life: { enabled?: boolean; effectiveFrom?: string; effectiveTo?: string } = {},
) => ({
  id,
  name,
  patronCategoryId: sel.patronCategoryId ?? null,
  itemTypeId: sel.itemTypeId ?? null,
  owningBranchId: sel.owningBranchId ?? null,
  shelvingLocationId: sel.shelvingLocationId ?? null,
  checkoutBranchId: sel.checkoutBranchId ?? null,
  pickupBranchId: sel.pickupBranchId ?? null,
  loanPolicyId: 'lp-14d',
  overdueFinePolicyId: 'fp-20c-day',
  lostItemFeePolicyId: 'lf-1',
  holdPolicyId: 'hp-1',
  noticePolicyId: 'np-1',
  maxLoansForRule: null,
  maxHoldsForRule: null,
  ageRestrictionMinYears: null,
  priority,
  enabled: life.enabled ?? true,
  effectiveFrom: life.effectiveFrom ?? null,
  effectiveTo: life.effectiveTo ?? null,
});

const RULES = [
  rule('r-default', 'Library default', {}),
  rule('r-child', 'Children', { patronCategoryId: 'cat-child' }),
  rule('r-dvd', 'DVDs', { itemTypeId: 'it-dvd' }),
  rule('r-child-dvd', 'Children + DVDs', { patronCategoryId: 'cat-child', itemTypeId: 'it-dvd' }),
  rule('r-branch-b', 'Branch B', { owningBranchId: 'br-b' }),
  rule('r-child-branch-b', 'Children at branch B', {
    patronCategoryId: 'cat-child',
    owningBranchId: 'br-b',
  }),
  rule('r-exception', 'One-off exception', { itemTypeId: 'it-dvd' }, 100),
];

/**
 * The wide rule set — every selector exercised, plus the three ways a rule can be
 * out of force.
 *
 * `RULES` above is six narrative cases a person can read. This one exists to be
 * SWEPT: 64 contexts × 3 instants against it enumerates the whole decision surface
 * of `resolveCirculationPolicy`, which is what phase 77's Rust core has to
 * reproduce. Six hand-written cases would let a Rust resolver that ignored
 * `shelvingLocationId` entirely pass the vector file.
 */
const WIDE_RULES = [
  rule('w-0-default', 'Library default', {}),
  rule('w-1-pickup', 'Pickup at B', { pickupBranchId: 'br-b' }),
  rule('w-2-checkout', 'Checked out at B', { checkoutBranchId: 'br-b' }),
  rule('w-3-shelf', 'Reference shelf', { shelvingLocationId: 'loc-ref' }),
  rule('w-4-owning', 'Owned by B', { owningBranchId: 'br-b' }),
  rule('w-5-type', 'DVDs', { itemTypeId: 'it-dvd' }),
  rule('w-6-cat', 'Children', { patronCategoryId: 'cat-child' }),
  rule('w-7-cat-type', 'Children + DVDs', {
    patronCategoryId: 'cat-child',
    itemTypeId: 'it-dvd',
  }),
  rule('w-8-shelf-checkout', 'Reference, checked out at B', {
    shelvingLocationId: 'loc-ref',
    checkoutBranchId: 'br-b',
  }),
  rule('w-9-all', 'Every selector', {
    patronCategoryId: 'cat-child',
    itemTypeId: 'it-dvd',
    owningBranchId: 'br-b',
    shelvingLocationId: 'loc-ref',
    checkoutBranchId: 'br-b',
    pickupBranchId: 'br-b',
  }),
  // Priority is the escape hatch: less specific, and it still wins — but only
  // while it is in force. Without the window it shadows `w-9-all` at every
  // instant, and the top of the specificity lattice becomes a rule that can never
  // win, so a Rust resolver that got 63 wrong would pass the sweep.
  rule('w-a-priority', 'Spring override', { pickupBranchId: 'br-b' }, 50, {
    effectiveTo: '2026-06-01T00:00:00Z',
  }),
  // In force only for the middle instant of the three the sweep uses.
  rule('w-b-window', 'Term-time rule', { patronCategoryId: 'cat-child' }, 200, {
    effectiveFrom: '2026-05-01T00:00:00Z',
    effectiveTo: '2026-06-01T00:00:00Z',
  }),
  // Never in force. A resolver that ignored `enabled` would return it everywhere,
  // because its priority beats everything.
  rule('w-c-disabled', 'Disabled', {}, 999, { enabled: false }),
];

const snapshots = {
  'snap-1': {
    version: 7,
    rules: RULES,
    loanPolicies,
    overdueFinePolicies: finePolicies,
    lostItemFeePolicies: {
      'lf-1': {
        id: 'lf-1',
        name: 'Replacement plus admin',
        chargeBasis: 'replacementPrice',
        fixedAmount: null,
        processingFee: { minorUnits: 500, currency: 'EUR' },
        agedToLostAfter: { value: 30, unit: 'days' },
        refundReplacementOnReturn: true,
        refundProcessingFeeOnReturn: false,
        refundWindow: { value: 90, unit: 'days' },
        stopOverdueAccrualOnLost: true,
        chargeOverdueUpToLost: true,
      },
    },
    holdPolicies: {
      'hp-1': {
        id: 'hp-1',
        name: 'Ordinary holds',
        holdsAllowed: true,
        requestTypes: ['hold'],
        onShelfHolds: 'allow',
        itemLevelHolds: 'allow',
        maxHoldsPerRecord: 1,
        maxHoldsTotal: 10,
        pickupPolicy: 'any',
        pickupBranchIds: [],
        holdShelfExpiry: { value: 7, unit: 'days' },
        shelfExpiryUsesCalendar: true,
        unfilledRequestExpiry: null,
        suspensionAllowed: true,
        maxSuspension: null,
        placementFee: null,
        notPickedUpFee: null,
        transitAllowed: true,
        maxTransitDays: 5,
      },
    },
    noticePolicies: {
      'np-1': {
        id: 'np-1',
        name: 'Standard notices',
        templates: [
          {
            id: 'nt-any',
            trigger: 'overdue',
            templateId: 'tpl-generic',
            branchId: null,
            patronCategoryId: null,
            offset: null,
          },
          {
            id: 'nt-cat',
            trigger: 'overdue',
            templateId: 'tpl-child',
            branchId: null,
            patronCategoryId: 'cat-child',
            offset: null,
          },
          {
            id: 'nt-branch',
            trigger: 'overdue',
            templateId: 'tpl-branch-b',
            branchId: 'br-b',
            patronCategoryId: null,
            offset: null,
          },
          {
            id: 'nt-both',
            trigger: 'overdue',
            templateId: 'tpl-both',
            branchId: 'br-b',
            patronCategoryId: 'cat-child',
            offset: null,
          },
        ],
      },
    },
    fixedDueDateSets: {},
    patronCategoryLimits: {},
    calendars,
  },
};

/**
 * The sweep snapshot. Same policy tables, the wide rule set, a different version
 * number so a vector that read the wrong snapshot fails loudly rather than
 * coincidentally passing.
 */
const SNAP_2 = { ...snapshots['snap-1'], version: 9, rules: WIDE_RULES };
(snapshots as Record<string, unknown>)['snap-2'] = SNAP_2;

// ---------------------------------------------------------------------------
// Vectors
// ---------------------------------------------------------------------------

const vectors: Record<string, unknown>[] = [];

// 1. RANK — all 64 selector combinations. The expectation is BIT SHIFTS, not the
//    named-weight table `rank.ts` uses.
for (let n = 0; n < 64; n += 1) {
  const selectors: Record<string, string | null> = {};
  SELECTORS.forEach((name, i) => {
    selectors[name] = (n >> (5 - i)) & 1 ? `x-${name}` : null;
  });
  vectors.push({
    kind: 'rank',
    id: `rank-${String(n).padStart(2, '0')}`,
    selectors,
    expectSpecificity: n,
  });
}

// 2. CIVIL — every wall-clock minute across both Athens DST transitions, plus a
//    sweep of ordinary days. Expectations from the linear scan.
const civilCases: { civil: CivilDateTime; note: string }[] = [];
for (let m = 0; m < 6 * 60; m += 15) {
  civilCases.push({
    civil: { year: 2026, month: 3, day: 29, hour: Math.floor(m / 60), minute: m % 60, second: 0 },
    note: 'spring forward',
  });
  civilCases.push({
    civil: { year: 2026, month: 10, day: 25, hour: Math.floor(m / 60), minute: m % 60, second: 0 },
    note: 'autumn back',
  });
}
// One date in every month, at four times of day: the offset is +02:00 for five
// of them and +03:00 for seven, and the boundary months are where an
// implementation that hard-coded either would be caught.
for (let month = 1; month <= 12; month += 1) {
  for (const hour of [0, 6, 12, 23]) {
    civilCases.push({
      civil: { year: 2026, month, day: 15, hour, minute: 30, second: 0 },
      note: 'monthly sweep',
    });
  }
}
// Midnight and the last minute of a day, on both sides of both transitions —
// the places an off-by-one in the hour reading shows up as an off-by-one DAY.
for (const [month, day] of [
  [3, 28],
  [3, 30],
  [10, 24],
  [10, 26],
  [12, 31],
] as const) {
  for (const [hour, minute] of [
    [0, 0],
    [23, 59],
  ] as const) {
    civilCases.push({
      civil: { year: 2026, month, day, hour, minute, second: 0 },
      note: 'day edge',
    });
  }
}
for (const [i, c] of civilCases.entries()) {
  const found = slowCandidates(TZ, c.civil);
  for (const dis of ['earlier', 'later'] as const) {
    const kind = found.length === 0 ? 'gap' : found.length === 1 ? 'unique' : 'ambiguous';
    // For a gap the reference has no instant to offer, so the vector records
    // only the KIND. The package's answer for a gap is an engineering choice
    // (the instant either side), not something a scan can discover.
    if (kind === 'gap') {
      vectors.push({
        kind: 'civil',
        id: `civil-${i}-${dis}`,
        timezone: TZ,
        civil: c.civil,
        disambiguation: dis,
        expectInstant: null,
        expectKind: 'gap',
      });
      continue;
    }
    const pick = dis === 'later' ? found[found.length - 1]! : found[0]!;
    vectors.push({
      kind: 'civil',
      id: `civil-${i}-${dis}`,
      timezone: TZ,
      civil: c.civil,
      disambiguation: dis,
      expectInstant: iso(pick),
      expectKind: kind,
    });
  }
}

// 3. DUE DATE — the acceptance cases and a sweep. Expectations for the plain
//    `keep` policies come from the slow reference; rolled ones assert the ROLL
//    REASONS, which is the trace half of the criterion.
const dueCases: { note: string; cal: string; lp: string; from: string; hold?: boolean }[] = [
  {
    note: '2-hour loan starting 01:30 on the spring-forward night',
    cal: 'cal-always-open',
    lp: 'lp-2h-inlibrary',
    from: '2026-03-28T23:30:00Z',
  },
  {
    note: '90 minutes across the spring forward',
    cal: 'cal-always-open',
    lp: 'lp-90m',
    from: '2026-03-28T23:30:00Z',
  },
  {
    note: '14 days across the spring forward',
    cal: 'cal-always-open',
    lp: 'lp-14d',
    from: '2026-03-20T10:00:00Z',
  },
  {
    note: '14 days across the autumn fallback',
    cal: 'cal-always-open',
    lp: 'lp-14d',
    from: '2026-10-15T10:00:00Z',
  },
  {
    note: '3 weeks in midsummer',
    cal: 'cal-always-open',
    lp: 'lp-3w',
    from: '2026-07-01T09:00:00Z',
  },
  {
    note: 'one month from 31 January clamps to 28 February',
    cal: 'cal-always-open',
    lp: 'lp-1m',
    from: '2026-01-31T09:00:00Z',
  },
  {
    note: 'indefinite staff loan',
    cal: 'cal-always-open',
    lp: 'lp-indefinite',
    from: '2026-05-05T09:00:00Z',
  },
  {
    note: 'a hold shortens the loan',
    cal: 'cal-always-open',
    lp: 'lp-hold-short',
    from: '2026-05-05T09:00:00Z',
    hold: true,
  },
  {
    note: 'max period caps three weeks at ten days',
    cal: 'cal-always-open',
    lp: 'lp-capped',
    from: '2026-05-05T09:00:00Z',
  },
];
for (let d = 0; d < 60; d += 1) {
  const from = Date.UTC(2026, 4, 1, 9, 0, 0) + d * 86_400_000;
  dueCases.push({ note: `sweep day ${d}`, cal: 'cal-always-open', lp: 'lp-14d', from: iso(from) });
}
for (const [i, c] of dueCases.entries()) {
  const from = new Date(c.from);
  const lp = loanPolicies[c.lp]!;
  let expect: string | null = null;
  if (lp['profile'] !== 'indefinite') {
    const period = lp['period'] as { value: number; unit: string };
    const effective =
      c.hold === true && lp['alternateCheckoutPeriodWithHolds'] !== null
        ? (lp['alternateCheckoutPeriodWithHolds'] as { value: number; unit: string })
        : period;
    expect = slowDue(from, effective, lp['maxPeriod'] as { value: number; unit: string } | null);
  }
  vectors.push({
    kind: 'dueDate',
    id: `due-${i}`,
    note: c.note,
    calendarId: c.cal,
    loanPolicyId: c.lp,
    from: c.from,
    ...(c.hold === true ? { hasOutstandingHold: true } : {}),
    expectDueAt: expect,
    expectRolls: c.hold === true ? ['holdShortened'] : c.lp === 'lp-capped' ? ['maxPeriodCap'] : [],
  });
}

/** The slow due date: elapsed for clock units, stepped days for civil ones. */
function slowDue(
  from: Date,
  period: { value: number; unit: string },
  maxPeriod: { value: number; unit: string } | null,
): string {
  const one = (p: { value: number; unit: string }): number => {
    if (p.unit === 'minutes') return from.getTime() + p.value * 60_000;
    if (p.unit === 'hours') return from.getTime() + p.value * 3_600_000;
    const civil = slowParts(TZ, from.getTime());
    if (p.unit === 'months') {
      const total = civil.year * 12 + (civil.month - 1) + p.value;
      const year = Math.floor(total / 12);
      const month = (total % 12) + 1;
      // Clamp by walking back until the date exists in that month.
      let day = civil.day;
      while (day > 28) {
        const probe = slowCandidates(TZ, {
          ...civil,
          year,
          month,
          day,
          hour: 12,
          minute: 0,
          second: 0,
        })[0];
        if (probe !== undefined && slowParts(TZ, probe).day === day) break;
        day -= 1;
      }
      const target = { ...civil, year, month, day };
      return slowCandidates(TZ, target)[slowCandidates(TZ, target).length - 1]!;
    }
    const days = p.unit === 'weeks' ? p.value * 7 : p.value;
    const target = slowAddDays(TZ, civil, days);
    const found = slowCandidates(TZ, target);
    return found[found.length - 1]!;
  };
  const base = one(period);
  if (maxPeriod === null) return iso(base);
  const cap = one(maxPeriod);
  return iso(Math.min(base, cap));
}

// 4. FINES — grace, intervals, caps, closed days.
const fineCases: { note: string; cal: string; fp: string; due: string; asOf: string }[] = [
  {
    note: 'returned on time',
    cal: 'cal-athens-simple',
    fp: 'fp-20c-day',
    due: '2026-05-05T12:00:00Z',
    asOf: '2026-05-05T11:00:00Z',
  },
  {
    note: 'one calendar day late',
    cal: 'cal-athens-simple',
    fp: 'fp-20c-day',
    due: '2026-05-05T12:00:00Z',
    asOf: '2026-05-06T08:00:00Z',
  },
  {
    note: 'inside a three-day grace',
    cal: 'cal-athens-simple',
    fp: 'fp-grace3',
    due: '2026-05-05T12:00:00Z',
    asOf: '2026-05-07T12:00:00Z',
  },
  {
    note: 'five days late with three days grace charges five',
    cal: 'cal-athens-simple',
    fp: 'fp-grace3',
    due: '2026-05-05T12:00:00Z',
    asOf: '2026-05-10T12:00:00Z',
  },
  {
    note: 'capped at five euro',
    cal: 'cal-athens-simple',
    fp: 'fp-max-5eur',
    due: '2026-01-05T12:00:00Z',
    asOf: '2026-04-05T12:00:00Z',
  },
  {
    note: 'charged at interval start: one minute late costs a day',
    cal: 'cal-athens-simple',
    fp: 'fp-start',
    due: '2026-05-05T12:00:00Z',
    asOf: '2026-05-05T12:01:00Z',
  },
  {
    note: 'hourly fine over four hours',
    cal: 'cal-always-open',
    fp: 'fp-hourly',
    due: '2026-05-05T12:00:00Z',
    asOf: '2026-05-05T16:00:00Z',
  },
];
for (let d = 1; d <= 40; d += 1) {
  const asOf = Date.UTC(2026, 4, 5, 12, 0, 0) + d * 86_400_000;
  fineCases.push({
    note: `day sweep +${d}`,
    cal: 'cal-athens-simple',
    fp: 'fp-20c-day',
    due: '2026-05-05T12:00:00Z',
    asOf: iso(asOf),
  });
  fineCases.push({
    note: `open-day sweep +${d}`,
    cal: 'cal-athens-simple',
    fp: 'fp-open-only',
    due: '2026-05-05T12:00:00Z',
    asOf: iso(asOf),
  });
}
for (const [i, c] of fineCases.entries()) {
  const fp = finePolicies[c.fp]!;
  const due = new Date(c.due);
  const asOf = new Date(c.asOf);
  const grace = fp['gracePeriod'] as { value: number; unit: string } | null;
  const graceEnd = grace === null ? null : new Date(slowDue(due, grace, null));
  const withinGrace = asOf > due && graceEnd !== null && asOf < graceEnd;
  let intervals = 0;
  if (asOf > due && !withinGrace) {
    const iv = fp['interval'] as { value: number; unit: string };
    let units: number;
    if (iv.unit === 'hours' || iv.unit === 'minutes') {
      const ms = iv.unit === 'hours' ? 3_600_000 : 60_000;
      units = (asOf.getTime() - due.getTime()) / (iv.value * ms);
    } else {
      const a = slowParts(TZ, due.getTime());
      const b = slowParts(TZ, asOf.getTime());
      let days = 0;
      let walk = a;
      while (!(walk.year === b.year && walk.month === b.month && walk.day === b.day)) {
        walk = slowAddDays(TZ, walk, 1);
        if (fp['countClosedDays'] === true || isOpenDayRef(c.cal, walk)) days += 1;
      }
      units = days / iv.value;
    }
    intervals = fp['chargeAt'] === 'intervalEnd' ? Math.floor(units) : Math.floor(units) + 1;
  }
  const per = fp['amountPerInterval'] as { minorUnits: number };
  let minor = intervals * per.minorUnits;
  const max = fp['maximumFine'] as { minorUnits: number } | null;
  if (max !== null && minor > max.minorUnits) minor = max.minorUnits;
  vectors.push({
    kind: 'fine',
    id: `fine-${i}`,
    note: c.note,
    calendarId: c.cal,
    finePolicyId: c.fp,
    dueAt: c.due,
    asOf: c.asOf,
    expectMinorUnits: minor,
    expectIntervals: intervals,
    expectWithinGrace: withinGrace,
  });
}

/** Is this calendar open on this civil date, read from the fixture directly? */
function isOpenDayRef(calId: string, civil: CivilDateTime): boolean {
  const cal = calendars[calId as keyof typeof calendars];
  const key = `${civil.year}-${String(civil.month).padStart(2, '0')}-${String(civil.day).padStart(2, '0')}`;
  for (const e of cal.exceptions) {
    const ek = `${e.date.year}-${String(e.date.month).padStart(2, '0')}-${String(e.date.day).padStart(2, '0')}`;
    if (ek === key) return e.intervals.length > 0;
  }
  // Weekday from the instant, not from a day number — independent of the package.
  const noon = slowCandidates(TZ, { ...civil, hour: 12, minute: 0, second: 0 })[0]!;
  const wd = new Date(noon).getUTCDay();
  return (cal.weekly.find((d) => d.weekday === wd)?.intervals.length ?? 0) > 0;
}

// 5. RESOLVE — which rule wins, and which matched and lost.
//
//    The expectation is computed by the reference below, NOT by `resolve.ts`:
//    specificity by bit shift over the selector list, ordering by an explicit
//    three-key comparator, in-force by direct date comparison. `rank.ts` uses a
//    named weight table and `isInForce`; two spellings of the same rule agreeing
//    is evidence, one spelling agreeing with itself is not.

type RuleLike = {
  id: string;
  priority: number;
  enabled: boolean;
  effectiveFrom: string | null;
  effectiveTo: string | null;
} & Record<string, unknown>;

/** Bit shifts, deliberately — the SQL generated column's arithmetic, not ours. */
function slowSpecificity(r: Record<string, unknown>): number {
  let n = 0;
  SELECTORS.forEach((name, i) => {
    if (r[name] !== null && r[name] !== undefined) n += 1 << (5 - i);
  });
  return n;
}

function slowInForce(r: RuleLike, atMs: number): boolean {
  if (!r.enabled) return false;
  if (r.effectiveFrom !== null && atMs < Date.parse(r.effectiveFrom)) return false;
  if (r.effectiveTo !== null && atMs >= Date.parse(r.effectiveTo)) return false;
  return true;
}

function slowResolve(
  rules: readonly RuleLike[],
  ctx: Record<string, string | null>,
  at: string,
): { matched: string; beaten: string[] } | null {
  const atMs = Date.parse(at);
  const candidates = rules
    .filter((r) => slowInForce(r, atMs))
    .filter((r) => SELECTORS.every((name) => r[name] === null || r[name] === ctx[name]));
  const ranked = [...candidates].sort((a, b) => {
    if (a.priority !== b.priority) return b.priority - a.priority;
    const sa = slowSpecificity(a);
    const sb = slowSpecificity(b);
    if (sa !== sb) return sb - sa;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
  if (ranked.length === 0) return null;
  return { matched: ranked[0]!.id, beaten: ranked.slice(1).map((r) => r.id) };
}

const emptyContext = (): Record<string, string | null> => ({
  patronCategoryId: null,
  itemTypeId: null,
  owningBranchId: null,
  shelvingLocationId: null,
  checkoutBranchId: null,
  pickupBranchId: null,
});

// 5a. Six narrative cases against `snap-1`, kept because a person reads them.
const resolveCases: { note: string; ctx: Record<string, string | null> }[] = [
  { note: 'nothing specific: the wildcard', ctx: {} },
  { note: 'category beats the default', ctx: { patronCategoryId: 'cat-child' } },
  { note: 'item type, and priority beats specificity', ctx: { itemTypeId: 'it-dvd' } },
  {
    note: 'category + item type, priority still winning',
    ctx: { patronCategoryId: 'cat-child', itemTypeId: 'it-dvd' },
  },
  {
    note: 'category outranks branch — 32 against 8',
    ctx: { patronCategoryId: 'cat-child', owningBranchId: 'br-b' },
  },
  { note: 'branch alone', ctx: { owningBranchId: 'br-b' } },
];
for (const [i, c] of resolveCases.entries()) {
  const ctx = { ...emptyContext(), ...c.ctx };
  const at = '2026-05-05T09:00:00Z';
  const want = slowResolve(RULES as unknown as RuleLike[], ctx, at);
  if (want === null) throw new Error(`resolve-${i} matches nothing; snap-1 has a wildcard`);
  vectors.push({
    kind: 'resolve',
    id: `resolve-${i}`,
    note: c.note,
    snapshotId: 'snap-1',
    context: ctx,
    at,
    expectMatchedRuleId: want.matched,
    expectBeatenRuleIds: want.beaten,
  });
}

// 5b. THE SWEEP. Every combination of the six selectors, at three instants that
//     straddle `w-b-window`'s effective range — 192 vectors that between them
//     reach every rule in `WIDE_RULES` and every branch of the comparator.
//
//     The values are chosen so a rule can both match and fail to match: `br-b`
//     for the three branch selectors and `loc-ref` for the location, because
//     those are the values `WIDE_RULES` names. A sweep over values no rule
//     mentions would resolve to the wildcard 64 times and prove nothing.
const SWEEP_VALUES: Record<string, string> = {
  patronCategoryId: 'cat-child',
  itemTypeId: 'it-dvd',
  owningBranchId: 'br-b',
  shelvingLocationId: 'loc-ref',
  checkoutBranchId: 'br-b',
  pickupBranchId: 'br-b',
};
const SWEEP_INSTANTS: readonly (readonly [string, string])[] = [
  ['2026-04-15T09:00:00Z', 'before the term-time rule is in force'],
  ['2026-05-15T09:00:00Z', 'inside the term-time window'],
  ['2026-06-15T09:00:00Z', 'after the term-time rule expires'],
];
for (const [ti, [at, when]] of SWEEP_INSTANTS.entries()) {
  for (let n = 0; n < 64; n += 1) {
    const ctx = emptyContext();
    SELECTORS.forEach((name, i) => {
      if ((n >> (5 - i)) & 1) ctx[name] = SWEEP_VALUES[name]!;
    });
    const want = slowResolve(WIDE_RULES as unknown as RuleLike[], ctx, at);
    if (want === null) throw new Error(`sweep ${ti}/${n} matches nothing; snap-2 has a wildcard`);
    vectors.push({
      kind: 'resolve',
      id: `resolve-sweep-${ti}-${String(n).padStart(2, '0')}`,
      note: `selectors 0b${n.toString(2).padStart(6, '0')}, ${when}`,
      snapshotId: 'snap-2',
      context: ctx,
      at,
      expectMatchedRuleId: want.matched,
      expectBeatenRuleIds: want.beaten,
    });
  }
}

const doc = {
  version: 1,
  generatedFor: '@libriant/circ-policy phase 12',
  note:
    'Golden vectors for the pure circulation-policy resolver. Run by node --test here and by ' +
    'cargo test in the offline Rust core (phase 77). Expectations are NOT produced by the ' +
    'implementation: rank uses bit shifts, time uses a one-minute linear scan over Intl, and ' +
    'civil-date arithmetic steps a day at a time. See scripts/build-vectors.ts.',
  fixtures: { calendars, loanPolicies, finePolicies, snapshots },
  vectors,
};

writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`);
// eslint-disable-next-line no-console
console.log(`wrote ${vectors.length} vectors to ${path.relative(process.cwd(), OUT)}`);
