-- The changelog trigger could not fire from an application connection.
--
-- Phase 9 shipped `lbr2_write_change_event()` with three unqualified names in
-- its body. A trigger function is re-resolved at RUNTIME under the CALLING
-- session's search_path, and every test phase 9 wrote happened to supply one:
-- the smoke modules do `SET search_path = lbr2, public`, and the census spec
-- only reads `pg_catalog`. From a connection with the default search_path —
-- which is every application connection — the first write to any replicated
-- table failed:
--
--     ERROR:  relation "change_events" does not exist
--     CONTEXT: PL/pgSQL function lbr2.lbr2_write_change_event() line 44
--
-- So `marc_records` could not be written at all, and phase 10 is blocked on it.
--
-- TWO BUGS, NOT ONE. The second is quieter and would have outlived the first.
-- `COALESCE(current_setting('libriant.actor_kind', true), 'system')` is correct
-- exactly once per backend. After a transaction has called `set_config(…, true)`
-- and committed, the setting is not NULL again — it is the EMPTY STRING —
-- so COALESCE returns `''` and the NEXT unattributed write on that pooled
-- connection fails with `22P02 invalid input value for enum audit_actor_kind:
-- ""`. It lands on whatever reuses the backend, which may be a nightly job
-- rather than the request that caused it. Measured, both the failure and the
-- fix.
--
-- WHY TG_TABLE_SCHEMA AND NOT A PINNED search_path. `ALTER FUNCTION … SET
-- search_path = lbr2, pg_catalog` fixes all three names and was measured to
-- work. It stores the schema name as text, so after phase 20's cutover
-- (`ALTER SCHEMA lbr2 RENAME TO public`) it names a schema that no longer
-- exists and every write fails again — also measured. Resolving through
-- `TG_TABLE_SCHEMA` instead is correct before and after the rename, and costs
-- nothing: 5,000 inserts took 290 ms pinned and 289 ms this way, because the
-- plan for a stable query string is cached.
--
-- ONLY THE FUNCTION CHANGES. The nine triggers created by the baseline are
-- untouched and keep their arguments, so `check:changelog-coverage` compares the
-- same set. Note that the census fixture cannot see this change at all — it
-- captures `pg_get_triggerdef`, which does not include the function body — which
-- is why `bib-write-path.spec.ts` carries a runtime regression test that drives
-- a real Prisma client instead.
--
-- Generated by `node scripts/gen-changelog-triggers.mjs`.

BEGIN;

SELECT pg_catalog.set_config(
  'search_path',
  pg_catalog.current_schema() || ', public',
  true
);

CREATE OR REPLACE FUNCTION lbr2_write_change_event() RETURNS trigger
  LANGUAGE plpgsql AS $lbr2_changelog$
DECLARE
  v_entity_kind  text := TG_ARGV[0];
  v_pk_column    text := TG_ARGV[1];
  v_has_branch   boolean := TG_ARGV[2]::boolean;
  v_row          jsonb;
  v_op           text;
  v_payload      jsonb;
  v_archived_col text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_row := pg_catalog.to_jsonb(OLD);
    v_op := 'delete';
    v_payload := NULL;
  ELSE
    v_row := pg_catalog.to_jsonb(NEW);
    v_payload := v_row;
    IF TG_OP = 'INSERT' THEN
      v_op := 'insert';
    ELSE
      v_op := 'update';
      -- A soft delete is a disappearance, not an edit. marc_records spells it
      -- deleted_at; everything else spells it archived_at.
      v_archived_col := CASE WHEN v_row ? 'deleted_at' THEN 'deleted_at' ELSE 'archived_at' END;
      IF v_row ? v_archived_col THEN
        IF pg_catalog.to_jsonb(OLD) ->> v_archived_col IS NULL
           AND v_row ->> v_archived_col IS NOT NULL THEN
          v_op := 'archive';
        ELSIF pg_catalog.to_jsonb(OLD) ->> v_archived_col IS NOT NULL
           AND v_row ->> v_archived_col IS NULL THEN
          v_op := 'restore';
        END IF;
      END IF;
    END IF;
  END IF;

  -- EVERY name resolved through TG_TABLE_SCHEMA. See the header for why the
  -- three obvious spellings of this statement are each wrong.
  EXECUTE pg_catalog.format(
    'INSERT INTO %1$I.change_events ('
    '  entity_kind, entity_id, op, branch_id, row_version, payload,'
    '  actor_kind, actor_id, device_id'
    ') VALUES ('
    '  $1, $2, $3, $4, pg_catalog.nextval(%2$L), $5,'
    '  COALESCE(NULLIF(pg_catalog.current_setting(''libriant.actor_kind'', true), ''''),'
    '           ''system'')::%1$I.audit_actor_kind,'
    '  NULLIF(pg_catalog.current_setting(''libriant.actor_id'', true), ''''),'
    '  NULLIF(pg_catalog.current_setting(''libriant.device_id'', true), '''')'
    ')',
    TG_TABLE_SCHEMA,
    TG_TABLE_SCHEMA || '.record_version_seq'
  )
  USING
    v_entity_kind,
    v_row ->> v_pk_column,
    v_op,
    CASE WHEN v_has_branch THEN v_row ->> 'branch_id' END,
    v_payload;

  RETURN NULL;  -- AFTER trigger; the return value is ignored.
END;
$lbr2_changelog$;

COMMIT;
