-- Holds: the queue, and the constraint that makes the acceptance criterion
-- enforceable rather than merely tested.
--
-- §6 phase 17. Two new tables, one enum, four CHECKs, two partial uniques, and
-- the foreign key phase 15 promised `item_transfers.hold_id` when it wrote "no
-- FK: holds is phase 17".
--
-- ============================================================================
-- THE THREE DECISIONS THIS FILE ENCODES
-- ============================================================================
--
-- 1. THE 1.0 BUG IS TURNED INTO A CONSTRAINT VIOLATION, NOT LEFT AS A WRONG
--    NUMBER.
--
--    §3: "The 1.0 blanket `> 0` decrement is correct only because the head
--    always leaves; with suspended holds being skipped it corrupts positions,
--    and a named regression test must fail under the old form."
--
--    The blanket form lives in three places in 1.0 — `reservations.service.ts`'s
--    promoter, `reservation-expiry.job.ts` and `loans.service.ts`'s return path
--    — and it is CORRECT there, because 1.0 has no suspension, so the hold that
--    leaves is always position 1 and decrementing everybody is decrementing
--    everybody behind it. The cancel path already uses the targeted form.
--
--    The moment a SUSPENDED hold can be skipped, the hold that leaves is not
--    the head. Concretely, five holds with #1 suspended, and #2 filled:
--
--      targeted   WHERE queue_position > 2   ->  1(susp), 2, 3, 4   correct
--      blanket    WHERE queue_position > 0   ->  0(susp), 2, 3, 4   position 0
--
--    `holds_position_is_one_based` makes the second line ABORT with `23514`
--    rather than commit a queue with no position 1 in it. That is what the named
--    regression test asserts, and a SQLSTATE is unambiguous and
--    order-independent where a multiset of positions is not: a subtly different
--    wrong implementation can still produce the right multiset.
--
-- 2. NO STATUS ENUM, AND THE ENDINGS ARE NULL TESTS.
--
--    A hold is open when `fulfilled_at`, `cancelled_at` and `expired_at` are all
--    NULL. Phase 15 measured the alternative on 200,053 rows and the numbers are
--    in `45-items.prisma`: a parameterised enum predicate seq-scans at 1470
--    buffers against 2 for a NULL predicate, still seq-scans with
--    `enable_seqscan = off` (so there is no index path at all), and
--    `ON CONFLICT … WHERE state = CAST($1::text AS …)` raises `42P10` while the
--    literal form works by hand in psql.
--
--    `holds_one_ending` is what makes the partial uniques mean what they say: a
--    row carrying two endings is excluded from an index by either of them, and a
--    second assignment would slip past `holds_one_assignment_per_item`. The same
--    argument `item_transfers_one_ending` already makes.
--
-- 3. A QUEUE POSITION EXISTS EXACTLY WHILE A HOLD IS WAITING.
--
--    Assigned is not queued: a hold that has been given a copy is still open and
--    is no longer in line. So `queue_position IS NOT NULL` iff the hold is open
--    AND unassigned — `holds_position_iff_waiting` — which is what lets the
--    partial unique on `(bib_id, queue_position)` be a plain NULL test and what
--    keeps a filled hold from occupying a slot nobody can have.
--
-- `prisma migrate deploy` does NOT wrap a migration file in a transaction, so
-- this file opens its own.

BEGIN;

SELECT pg_catalog.set_config(
  'search_path',
  pg_catalog.current_schema() || ', public',
  true
);

-- ---------------------------------------------------------------------------
-- Generated by `prisma migrate diff`, with the permanently-allowlisted drift
-- removed: four trigram/pattern index drops, three generated-column drops, and
-- the marc_records sequence-default pair.
-- ---------------------------------------------------------------------------

-- CreateEnum
CREATE TYPE "hold_level" AS ENUM ('title', 'volume', 'item');

-- CreateTable
CREATE TABLE "holds" (
    "id" TEXT NOT NULL,
    "bib_id" TEXT NOT NULL,
    "level" "hold_level" NOT NULL DEFAULT 'title',
    "item_id" TEXT,
    "volume" TEXT,
    "patron_id" TEXT NOT NULL,
    "request_type" "hold_request_type" NOT NULL DEFAULT 'hold',
    "pickup_branch_id" TEXT NOT NULL,
    "queue_position" INTEGER,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "assigned_item_id" TEXT,
    "assigned_at" TIMESTAMPTZ(3),
    "awaiting_pickup_since" TIMESTAMPTZ(3),
    "shelf_expires_at" TIMESTAMPTZ(3),
    "suspended_from" DATE,
    "suspended_until" DATE,
    "request_expires_at" TIMESTAMPTZ(3),
    "fulfilled_at" TIMESTAMPTZ(3),
    "fulfilled_by_loan_id" TEXT,
    "cancelled_at" TIMESTAMPTZ(3),
    "cancelled_by_user_id" TEXT,
    "cancelled_reason" TEXT,
    "expired_at" TIMESTAMPTZ(3),
    "expired_kind" TEXT,
    "hold_policy_id" TEXT NOT NULL,
    "applied_rule_id" TEXT NOT NULL,
    "policy_snapshot" JSONB NOT NULL,
    "group_id" TEXT,
    "source" "event_source" NOT NULL DEFAULT 'desk',
    "placed_by_user_id" TEXT,
    "notes" TEXT,
    "placed_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(3) NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "holds_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "hold_groups" (
    "id" TEXT NOT NULL,
    "patron_id" TEXT NOT NULL,
    "name" TEXT,
    "resolved_at" TIMESTAMPTZ(3),
    "resolved_by_hold_id" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "hold_groups_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "holds_queue_idx" ON "holds"("bib_id", "priority" DESC, "queue_position");

-- CreateIndex
CREATE INDEX "holds_patron_idx" ON "holds"("patron_id", "placed_at");

-- CreateIndex
CREATE INDEX "hold_groups_patron_id_idx" ON "hold_groups"("patron_id");

-- AddForeignKey
ALTER TABLE "item_transfers" ADD CONSTRAINT "item_transfers_hold_id_fkey" FOREIGN KEY ("hold_id") REFERENCES "holds"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "holds" ADD CONSTRAINT "holds_bib_id_fkey" FOREIGN KEY ("bib_id") REFERENCES "marc_records"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "holds" ADD CONSTRAINT "holds_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "patrons"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "holds" ADD CONSTRAINT "holds_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "holds" ADD CONSTRAINT "holds_assigned_item_id_fkey" FOREIGN KEY ("assigned_item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "holds" ADD CONSTRAINT "holds_pickup_branch_id_fkey" FOREIGN KEY ("pickup_branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "holds" ADD CONSTRAINT "holds_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "hold_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hold_groups" ADD CONSTRAINT "hold_groups_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "patrons"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- The two partial uniques §3 names, and the CHECKs that make them mean it
-- ---------------------------------------------------------------------------

-- §3's own phrase: "`holds_one_assignment_per_item` making a double-assigned
-- item impossible". A pure NULL predicate — see decision 2 in the header for why
-- it is not `WHERE status = 'assigned'`.
--
-- `assigned_item_id` is nullable and a partial unique treats NULLs as distinct
-- anyway, so the extra `IS NOT NULL` is not redundant: it keeps the index to the
-- handful of rows that actually hold a copy, instead of one entry per waiting
-- reader.
CREATE UNIQUE INDEX holds_one_assignment_per_item
  ON holds (assigned_item_id)
  WHERE assigned_item_id IS NOT NULL
    AND fulfilled_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL;

-- Two readers cannot share a slot. Contiguity and 1-basedness are AGGREGATE
-- properties no constraint reaches, so they live in the named regression test
-- and in `holds_position_is_one_based` below; uniqueness is the half a database
-- can prove, and it is the half that stops a rebalance colliding with a
-- placement.
--
-- NOTE FOR A LATER PHASE: `ON CONFLICT` can never arbitrate on this index to
-- pick the next free slot. Postgres requires an arbiter to match the index's
-- columns AND its predicate, and an upsert that wanted "the next position" would
-- have to know the position before it could name it. Positions are allocated by
-- `max(queue_position) + 1` under the `bib:` advisory lock, which is what makes
-- that read-then-write safe.
CREATE UNIQUE INDEX holds_one_hold_per_position
  ON holds (bib_id, queue_position)
  WHERE queue_position IS NOT NULL;

-- One reader, one live hold per record. A second is a mistake at a desk, not a
-- second place in the queue — and without this a double-click puts a reader in
-- line twice and hands them two copies.
CREATE UNIQUE INDEX holds_one_live_per_patron_bib
  ON holds (patron_id, bib_id)
  WHERE fulfilled_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL;

ALTER TABLE holds
  -- Decision 2. Exactly one ending, or none.
  ADD CONSTRAINT holds_one_ending
    CHECK (pg_catalog.num_nonnulls(fulfilled_at, cancelled_at, expired_at) <= 1),
  -- Decision 3. A position exists exactly while the hold is waiting.
  ADD CONSTRAINT holds_position_iff_waiting
    CHECK ((queue_position IS NOT NULL)
           = (assigned_item_id IS NULL
              AND fulfilled_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL)),
  -- DECISION 1, and the phase's acceptance criterion made enforceable. The 1.0
  -- blanket decrement aborts here with 23514 the first time a suspended hold at
  -- position 1 is skipped.
  ADD CONSTRAINT holds_position_is_one_based
    CHECK (queue_position IS NULL OR queue_position >= 1),
  -- A suspension is a window, not a moment.
  ADD CONSTRAINT holds_suspension_window
    CHECK (suspended_from IS NULL OR suspended_until IS NULL OR suspended_from <= suspended_until),
  -- An item-level hold names an item; a title-level one must not. The `volume`
  -- text is the same shape for a volume hold. Without this a request can claim a
  -- level it does not carry the data for, and the promotion filter then silently
  -- treats it as a title hold — which hands a reader the wrong physical thing.
  ADD CONSTRAINT holds_level_carries_its_target
    CHECK ((level <> 'item' OR item_id IS NOT NULL)
           AND (level <> 'volume' OR volume IS NOT NULL)
           AND (level <> 'title' OR (item_id IS NULL AND volume IS NULL))),
  -- The two halves of a fulfilment, and of an expiry. Half a record is a row
  -- somebody half-wrote.
  ADD CONSTRAINT holds_fulfilment_pair
    CHECK ((fulfilled_at IS NULL) = (fulfilled_by_loan_id IS NULL)),
  ADD CONSTRAINT holds_expiry_pair
    CHECK ((expired_at IS NULL) = (expired_kind IS NULL)),
  ADD CONSTRAINT holds_expired_kind_known
    CHECK (expired_kind IS NULL OR expired_kind IN ('shelf', 'request')),
  -- Collectable implies assigned. A hold cannot be on a shelf without a copy on
  -- it, and this is the state the routed-hold criterion turns on: for the whole
  -- of a transit the copy is assigned and `awaiting_pickup_since` is NULL.
  ADD CONSTRAINT holds_collectable_implies_assigned
    CHECK (awaiting_pickup_since IS NULL OR assigned_item_id IS NOT NULL),
  ADD CONSTRAINT holds_shelf_expiry_implies_collectable
    CHECK (shelf_expires_at IS NULL OR awaiting_pickup_since IS NOT NULL);

ALTER TABLE hold_groups
  ADD CONSTRAINT hold_groups_resolution_pair
    CHECK ((resolved_at IS NULL) = (resolved_by_hold_id IS NULL));

-- The hold shelf, and the pull list: two reads a desk does every morning.
--
-- Both are partial on a NULL test rather than on a status, for decision 2's
-- reason. The pull list is "assigned, not yet collectable" — the copies a
-- librarian has to physically fetch; the shelf is "collectable", ordered by the
-- date the reader will be told.
CREATE INDEX holds_pull_list_idx
  ON holds (pickup_branch_id, assigned_at)
  WHERE assigned_item_id IS NOT NULL AND awaiting_pickup_since IS NULL
    AND fulfilled_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL;

CREATE INDEX holds_shelf_idx
  ON holds (pickup_branch_id, shelf_expires_at)
  WHERE awaiting_pickup_since IS NOT NULL
    AND fulfilled_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL;

-- The request-expiry sweep, and the suspension resume. Both scan a small live
-- set out of a table that grows for ever.
CREATE INDEX holds_request_expiry_idx
  ON holds (request_expires_at)
  WHERE request_expires_at IS NOT NULL
    AND fulfilled_at IS NULL AND cancelled_at IS NULL AND expired_at IS NULL;

-- "How many copies does this record have?", which nothing could answer without a
-- scan.
--
-- `items_shelf_available_idx` is PARTIAL on `is_shelf_available`, so it serves
-- "how many are ON THE SHELF" and is useless for the denominator.
-- `countCirculationState` asks for both on every checkout and every hold
-- placement, because `allCopiesAvailable` is the ratio — and measured on a fresh
-- schema the denominator was a Seq Scan on `items`, which on a real catalogue is
-- the whole table on the hottest path in the building.
--
-- PARTIAL, and the predicate is doing two jobs. It matches the subquery's own
-- literal `archived_at IS NULL`, so the planner can prove it; and it makes the
-- index USELESS to the phase-15 hold-promotion probe, which carries no such
-- clause. That second job is the reason for the allowlist entry rather than a
-- plain `@@index([bibId])`: a plain index competes with
-- `items_shelf_available_idx` on an empty table, the planner picks either at
-- equal cost, and phase 15's `items.spec.ts` assertion that the probe uses the
-- two-column partial index starts flapping — an assertion about a real plan,
-- broken by an index that is worse for that query.
--
-- Prisma has no partial-index concept and does not SEE one either: `migrate
-- diff` emits no DROP for a partial btree index, which is why
-- `circulation_rules_default_singleton` and the three partial uniques below need
-- no allowlist entry in `check-schema-drift.ts` and this one does not either.
-- (Verified by adding an entry and watching the gate refuse it as an exception
-- that no longer describes the tree.)
CREATE INDEX items_bib_idx ON items (bib_id) WHERE archived_at IS NULL;

-- ---------------------------------------------------------------------------
-- Changelog triggers
-- ---------------------------------------------------------------------------
--
-- §4.2: trigger-written, never application-emitted. Both are `@replicated` and
-- `branch = false`: a hold belongs to a library, and `pickup_branch_id` is where
-- a reader will collect it rather than a partition of the feed — a branch-scoped
-- consumer that filtered on it would miss every hold routed TO it from
-- somewhere else, which is precisely the interesting case.
CREATE TRIGGER holds_changelog
  AFTER INSERT OR UPDATE OR DELETE ON holds
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('hold', 'id', false);

CREATE TRIGGER hold_groups_changelog
  AFTER INSERT OR UPDATE OR DELETE ON hold_groups
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('hold_group', 'id', false);

COMMIT;
