export { controlDb, disconnectControlDb } from './client.js';

// Re-export the generated Prisma types so consumers can import everything
// from `@libriant/db-control` without dipping into @prisma/client directly.
export {
  Prisma,
  PrismaClient,
  // Enums
  TenantStatus,
  UserRole,
  UserStatus,
  AdminRole,
  AdminStatus,
  FeatureType,
  BillingMode,
  SubscriptionStatus,
  SupportKeyStatus,
  SupportSessionEndReason,
  AnnouncementSeverity,
  SystemModeKind,
  SystemModeScope,
  AuditActorType,
  EmailOutboxStatus,
  EmailMessageKind,
  ImportEntityKind,
  ImportSourceFormat,
  ImportStatus,
  ImportDuplicateMode,
  MaintenanceKind,
  MaintenanceScope,
  MaintenanceStatus,
  ExportFormat,
  ExportScope,
  ExportStatus,
  ExportRequesterKind,
  LibraryType,
  LibraryEditRequestStatus,
  ApplicationStatus,
} from '@prisma/client';

export type {
  Cell,
  Tenant,
  TenantDbCredential,
  User,
  PlanFeature,
  Plan,
  PlanFeatureValue,
  TenantPlanOverride,
  Subscription,
  BillingAccount,
  StripeWebhookEvent,
  AdminUser,
  SupportKey,
  SupportSession,
  SupportActionLog,
  SupportRedemptionAttempt,
  AuditEvent,
  Announcement,
  AnnouncementDelivery,
  SystemModeEvent,
  EmailOutbox,
  ImportBatch,
  ImportRowIssue,
  PlatformSetting,
  MaintenanceRun,
  ExportJob,
  LibraryEditRequest,
  Application,
} from '@prisma/client';
