import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import type { NestExpressApplication } from '@nestjs/platform-express';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import { randomBytes } from 'node:crypto';
import { generateSync } from 'otplib';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import request from 'supertest';
import { Client as PgClient } from 'pg';
import { controlDb } from '@libriant/db-control';
import { AppModule } from '../../src/app.module.js';
import { HttpExceptionFilter } from '../../src/platform/http-exception.filter.js';
import { RedisService } from '../../src/platform/redis.service.js';
import { loadEnv } from '../../src/config/env.js';
import { listenOnce } from './listen-once.js';
import { declareBillingPosture } from './billing-posture.js';

declareBillingPosture(
  'unenforced',
  'privacy-legal-07 is a consent-and-audit boundary, not a plan gate. Subscriptions are OFF in ' +
    'the shipped configuration, which is what the export endpoint has to behave correctly ' +
    'under; turning them on would only add a 402 surface that has nothing to do with whether ' +
    'a Libriant admin may take a copy of a library.',
);

/**
 * privacy-legal-07, end to end over HTTP.
 *
 * The audit found that `POST /admin/exports` was gated on `@AdminRoles('owner')`
 * and nothing else: `createForAdmin` inserted an `export_jobs` row and enqueued
 * the job, writing no control-plane `audit_log` row, nothing in the target
 * library's own `audit_log`, and sending no notice — while the very same
 * platform requires a tenant-issued, single-use, expiring `SupportKey` before an
 * admin may impersonate a single tenant user. Export yielded strictly more data
 * than impersonation and asked for strictly less.
 *
 * This file drives the real endpoints — real signup, a real MFA-enrolled admin,
 * a real key generated by the library and redeemed at `POST /admin/support/redeem`
 * — and asserts, in order:
 *
 *   1. with no support session, a tenant-scoped export is REFUSED and leaves
 *      no `export_jobs` row and no audit row behind;
 *   2. once the library consents, the same request is accepted AND lands in
 *      both ledgers — the control-plane `audit_log` with the admin, IP,
 *      user-agent and session id, and the LIBRARY's own `audit_log`, where
 *      `GET /t/:slug/audit` shows it flagged as having happened via support;
 *   3. the library's own export list attributes it to Libriant rather than
 *      showing it unattributed beside its own exports;
 *   4. a disclosure e-mail is enqueued;
 *   5. downloading the artifact is recorded BEFORE a byte is streamed;
 *   6. a `control`-scope dump needs no session (no library can consent to it)
 *      but is still recorded;
 *   7. a `all`-scope dump — which no library can consent to either — is written
 *      into every included library's own log.
 *
 * Pre-reqs: `pnpm db:up`, or the audit environment.
 */

let app: NestExpressApplication;
let slug: string;
let tenantId: string;
let ownerCookie = '';
let adminEmail = '';
let adminId = '';
let adminCookie = '';
let totpSecret = '';
let supportSessionId = '';
let tenantExportId = '';

const ownerPassword = 'export-consent-test-pw-1';
const adminPassword = 'export-consent-admin-pw-1';
const TEST_IP = '203.0.113.44';
const TEST_UA = 'export-consent-test/1.0';
const env = loadEnv();

function cookieMatching(res: request.Response, re: RegExp): string {
  const raw = res.headers['set-cookie'] as unknown as string[] | string | undefined;
  const cookies = Array.isArray(raw) ? raw : raw ? [raw] : [];
  const found = cookies.find((c) => re.test(c));
  if (!found) throw new Error(`no cookie matching ${re} in ${JSON.stringify(cookies)}`);
  return found.split(';')[0]!;
}

async function dropTenantDb(id: string) {
  const dbName = `tenant_${id.replace(/[^a-z0-9_]/gi, '_').toLowerCase()}`;
  const admin = new PgClient({ connectionString: env.pgSuperuserUrl });
  await admin.connect();
  try {
    await admin.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [dbName],
    );
    await admin.query(`DROP DATABASE IF EXISTS "${dbName}"`);
  } finally {
    await admin.end();
  }
}

type AuditItem = {
  action: string;
  actorType: string;
  actorLabel: string | null;
  targetType: string | null;
  targetId: string | null;
  viaSupport: boolean;
  after: Record<string, unknown> | null;
};

/**
 * Read the librarian's OWN audit screen until `match` appears.
 *
 * Unlike the impersonation interceptor's rows, the export disclosure is awaited
 * before the 202 is returned — it is a precondition of enqueueing, not an
 * after-the-fact note. The poll is still here because `GET /t/:slug/audit` goes
 * through a separate tenant client and a cold pool can lag the write by a tick;
 * a first-try hit is the normal case.
 */
async function waitForTenantAudit(
  match: (i: AuditItem) => boolean,
  what: string,
  timeoutMs = 15_000,
): Promise<AuditItem> {
  const deadline = Date.now() + timeoutMs;
  let seen: AuditItem[] = [];
  while (Date.now() < deadline) {
    const res = await request(app.getHttpServer())
      .get(`/t/${slug}/audit`)
      .set('Cookie', ownerCookie)
      .expect(200);
    seen = res.body.items as AuditItem[];
    const hit = seen.find(match);
    if (hit) return hit;
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error(
    `no tenant audit row for ${what} within ${timeoutMs}ms; saw ${JSON.stringify(seen.map((i) => i.action))}`,
  );
}

/** Latest control-plane audit row for our admin + action, or null. */
async function controlAudit(action: string) {
  return controlDb.auditEvent.findFirst({
    where: { actorId: adminId, action },
    orderBy: { occurredAt: 'desc' },
  });
}

beforeAll(async () => {
  app = await NestFactory.create<NestExpressApplication>(AppModule, {
    rawBody: true,
    logger: ['error', 'warn'],
  });
  app.set('trust proxy', true);
  app.use(cookieParser());
  app.useGlobalFilters(new HttpExceptionFilter());
  await app.init();
  await listenOnce(app);

  const redis = app.get(RedisService);
  const deadline = Date.now() + 5_000;
  while (Date.now() < deadline) {
    if (await redis.ping()) break;
    await new Promise((r) => setTimeout(r, 100));
  }

  const http = app.getHttpServer();

  slug = 'exp-' + randomBytes(3).toString('hex');
  await request(http)
    .post('/auth/signup')
    .send({
      libraryName: `Export Consent ${slug}`,
      slug,
      fullName: `Owner ${slug}`,
      email: `owner@${slug}.test`,
      password: ownerPassword,
      acceptLegal: true,
      libraryType: 'public',
      addressStreet: '1 Library St',
      addressCity: 'Athens',
      addressPostalCode: '10000',
      addressCountry: 'GR',
    })
    .expect(201);
  const tenant = await controlDb.tenant.findUnique({ where: { slug }, select: { id: true } });
  tenantId = tenant!.id;

  const login = await request(http)
    .post('/auth/login')
    .send({ slug, identifier: `owner@${slug}.test`, password: ownerPassword })
    .expect(200);
  ownerCookie = cookieMatching(login, /^(__Host-)?libriant_session=/);

  // `owner` tier: POST /admin/exports carries @AdminRoles('owner'), so this is
  // the only admin who can reach the endpoint at all — the highest-privileged
  // one, and therefore the one the consent gate has to hold against.
  adminEmail = `export-consent-${randomBytes(3).toString('hex')}@test.local`;
  const adminRow = await controlDb.adminUser.create({
    data: {
      email: adminEmail,
      fullName: 'Export Consent Test Owner',
      role: 'owner',
      status: 'active',
      passwordHash: bcrypt.hashSync(adminPassword, 8),
      mfaSecretCipher: randomBytes(32),
      mfaNonce: randomBytes(12),
      mfaKeyId: 'test',
    },
    select: { id: true },
  });
  adminId = adminRow.id;

  const adminLogin = await request(http)
    .post('/admin/auth/login')
    .send({ email: adminEmail, password: adminPassword })
    .expect(200);
  adminCookie = cookieMatching(adminLogin, /^(__Host-)?libriant_admin=/);

  const setup = await request(http).post('/admin/mfa/setup').set('Cookie', adminCookie).expect(200);
  totpSecret = setup.body.secret;
  await request(http)
    .post('/admin/mfa/verify')
    .set('Cookie', adminCookie)
    .send({ code: generateSync({ secret: totpSecret }) })
    .expect(200);
}, 120_000);

afterAll(async () => {
  if (adminId) {
    await controlDb.exportJob
      .deleteMany({ where: { requestedByKind: 'admin', requestedById: adminId } })
      .catch(() => undefined);
    await controlDb.auditEvent.deleteMany({ where: { actorId: adminId } }).catch(() => undefined);
  }
  if (tenantId) {
    await controlDb.exportJob
      .deleteMany({ where: { targetTenantId: tenantId } })
      .catch(() => undefined);
    await controlDb.tenant.deleteMany({ where: { id: tenantId } }).catch(() => undefined);
    await dropTenantDb(tenantId).catch(() => undefined);
  }
  if (adminEmail) {
    await controlDb.adminUser.deleteMany({ where: { email: adminEmail } }).catch(() => undefined);
  }
  if (app) await app.close();
}, 60_000);

describe('a Libriant admin cannot copy one library without that library saying so', () => {
  it('refuses a tenant-scoped export when no support session is open', async () => {
    const res = await request(app.getHttpServer())
      .post('/admin/exports')
      .set('Cookie', adminCookie)
      .set('X-Real-IP', TEST_IP)
      .set('User-Agent', TEST_UA)
      .send({ format: 'json', scope: 'tenant', tenantId })
      .expect(403);

    expect(res.body.message).toMatch(/support key/i);

    // A refused export must leave nothing half-started: no job row, and no
    // audit row claiming an export that never happened.
    const jobs = await controlDb.exportJob.findMany({ where: { targetTenantId: tenantId } });
    expect(jobs).toHaveLength(0);
    expect(await controlAudit('tenant.exported')).toBeNull();
  });

  it('accepts it once the library issues a key, and lands it in BOTH ledgers', async () => {
    const http = app.getHttpServer();

    // The library consents, through the product's own flow.
    const key = await request(http)
      .post(`/t/${slug}/support/keys`)
      .set('Cookie', ownerCookie)
      .expect(200);
    await request(http)
      .post('/admin/support/redeem')
      .set('Cookie', adminCookie)
      .send({ code: key.body.code, totp: generateSync({ secret: totpSecret }) })
      .expect(200);

    const session = await controlDb.supportSession.findFirst({
      where: { tenantId, adminId, endedAt: null },
      select: { id: true },
    });
    expect(session).toBeTruthy();
    supportSessionId = session!.id;

    const res = await request(http)
      .post('/admin/exports')
      .set('Cookie', adminCookie)
      .set('X-Real-IP', TEST_IP)
      .set('User-Agent', TEST_UA)
      .send({ format: 'json', scope: 'tenant', tenantId })
      .expect(202);

    tenantExportId = res.body.export.id;
    expect(res.body.export.scope).toBe('tenant');
    expect(res.body.export.requestedByKind).toBe('admin');

    // --- ledger 1: the control plane ---------------------------------------
    const control = await controlAudit('tenant.exported');
    expect(control, 'no control-plane audit row for the export').toBeTruthy();
    expect(control!.tenantId).toBe(tenantId);
    expect(control!.actorType).toBe('admin');
    expect(control!.targetType).toBe('export');
    expect(control!.targetId).toBe(tenantExportId);
    expect(control!.ip).toBe(TEST_IP);
    expect(control!.userAgent).toBe(TEST_UA);
    const controlAfter = control!.afterJson as Record<string, unknown>;
    expect(controlAfter.supportSessionId).toBe(supportSessionId);
    expect(controlAfter.tenantsNotified).toBe(1);
    expect(controlAfter.tenantsNotFound).toEqual([]);

    // --- ledger 2: the log the LIBRARY can actually open --------------------
    const row = await waitForTenantAudit(
      (i) => i.action === 'tenant.exported' && i.targetId === tenantExportId,
      'the admin export',
    );
    expect(row.actorType).toBe('admin');
    expect(row.actorLabel).toBe('Export Consent Test Owner');
    expect(row.viaSupport).toBe(true);
    expect(row.after?.requestedBy).toBe('libriant_staff');
    expect(row.after?.supportSessionId).toBe(supportSessionId);
    expect(row.after?.scope).toBe('tenant');
  }, 90_000);

  it("attributes it to Libriant in the library's own export list", async () => {
    const res = await request(app.getHttpServer())
      .get(`/t/${slug}/exports`)
      .set('Cookie', ownerCookie)
      .expect(200);
    const mine = (res.body.exports as Array<Record<string, unknown>>).find(
      (e) => e.id === tenantExportId,
    );
    // The audit's verification noted this row was already visible but stripped
    // of every attribution — indistinguishable from one a librarian started.
    expect(mine, 'the admin export is missing from the library’s own list').toBeTruthy();
    expect(mine!.requestedByKind).toBe('admin');
  });

  it('enqueues a disclosure e-mail to the library', async () => {
    const mail = await controlDb.emailOutbox.findFirst({
      where: { tenantId, idempotencyKey: `export.disclosed:${tenantExportId}:${tenantId}` },
    });
    expect(mail, 'no disclosure e-mail was enqueued').toBeTruthy();
    expect(mail!.toEmail).toBe(`owner@${slug}.test`);
    expect(mail!.bodyMarkdown).toContain(supportSessionId);
  });

  it('records a download attempt before streaming anything', async () => {
    // The job is still `queued` (no worker runs in this suite), so the stream
    // itself 400s. That is exactly the case worth asserting: the audit write is
    // awaited BEFORE streamExport, so even a download that produced no bytes is
    // on the record — an artifact outlives the window that authorised it.
    await request(app.getHttpServer())
      .get(`/admin/exports/${tenantExportId}/download`)
      .set('Cookie', adminCookie)
      .set('X-Real-IP', TEST_IP)
      .set('User-Agent', TEST_UA)
      .expect(400);

    const row = await controlAudit('export.downloaded');
    expect(row, 'the download was not recorded').toBeTruthy();
    expect(row!.targetId).toBe(tenantExportId);
    expect(row!.ip).toBe(TEST_IP);
  });

  it('lets a control-plane dump through without a session, but still records it', async () => {
    const res = await request(app.getHttpServer())
      .post('/admin/exports')
      .set('Cookie', adminCookie)
      .set('X-Real-IP', TEST_IP)
      .set('User-Agent', TEST_UA)
      // csv, not sql: a SQL dump of the control DB is refused outright (EXP-004).
      .send({ format: 'csv', scope: 'control' })
      .expect(202);

    const control = await controlAudit('platform.exported');
    expect(control).toBeTruthy();
    expect(control!.targetId).toBe(res.body.export.id);
    expect(control!.tenantId).toBeNull();
    const after = control!.afterJson as Record<string, unknown>;
    expect(after.scope).toBe('control');
    // Nobody to tell: the control database holds no library's member registry.
    expect(after.tenantsNotified).toBe(0);
    expect(after.supportSessionId).toBeNull();
  });

  it("writes a platform-wide dump into the library's own log too", async () => {
    const res = await request(app.getHttpServer())
      .post('/admin/exports')
      .set('Cookie', adminCookie)
      .set('X-Real-IP', TEST_IP)
      .set('User-Agent', TEST_UA)
      .send({ format: 'csv', scope: 'all' })
      .expect(202);
    const allExportId = res.body.export.id as string;

    // No single library can consent to a platform-wide copy, so there is no
    // session to attach — but every library it covers still gets told.
    const row = await waitForTenantAudit(
      (i) => i.action === 'tenant.exported' && i.targetId === allExportId,
      'the platform-wide export',
    );
    expect(row.after?.scope).toBe('all');
    expect(row.after?.supportSessionId).toBeNull();
    expect(row.viaSupport).toBe(false);

    const control = await controlDb.auditEvent.findFirst({
      where: { actorId: adminId, action: 'platform.exported', targetId: allExportId },
    });
    expect(control).toBeTruthy();
    const after = control!.afterJson as Record<string, unknown>;
    expect(after.scope).toBe('all');
    // At least our own library was reached; other tenants in a shared audit
    // database may be leftovers whose physical database is long gone, and the
    // fan-out records those in `tenantsNotFound` rather than failing.
    expect(after.tenantsNotified as number).toBeGreaterThanOrEqual(1);
  }, 180_000);
});
