-- The rules matrix, the five policies it names, and the counter every pod watches.
--
-- §6 phase 13. `packages/circ-policy/src/types.ts` is the column spec — it says
-- so in its own header — and every column below is a field of a type in that
-- file. Where a decision had to be made it is about ENCODING, and each one is
-- argued in the model docblocks rather than repeated here.
--
-- EIGHTEEN TABLES. `BASELINE-SCOPE.json` flips FOURTEEN existing entries from
-- `deferred` to `created` and gains FOUR new ones in the same commit, because
-- §3 never names them: `calendar_exception_hours` and
-- `hold_policy_pickup_branches` are decompositions §3 does not make,
-- `notice_policy_templates` is a new name (`notice_templates` stays deferred to
-- phase 22 for the RENDERABLE template; this is the selector that points at
-- one), and `circulation_settings` is one boolean rather than the cross-cutting
-- `tenant_settings` singleton, which also stays deferred.
--
-- One of the fourteen moves across a milestone boundary and the manifest argues
-- it: `patron_categories` was `9c/14/32` because §3 lists it under Patrons, and
-- it comes forward because the matrix selects on it and a rule naming a category
-- that does not exist is a rule that silently never matches.
--
-- ============================================================================
-- WHAT PRISMA CANNOT EXPRESS, AND THEREFORE WHAT THE HAND-WRITTEN HALF IS FOR
-- ============================================================================
--
--   * `circulation_rules.specificity` — a GENERATED STORED column. It is the
--     tiebreak the whole matrix ranks on, and two code paths computing it
--     differently is the most damaging bug available here. Absent from the
--     datamodel; the drop `migrate diff` proposes is allowlisted in
--     `scripts/check-schema-drift.ts` beside `items.is_shelf_available`.
--   * The two partial unique indexes §3 specifies on `circulation_rules`.
--   * Thirty-one CHECK constraints. Twenty-two of them are `(x IS NULL) = (y IS
--     NULL)` on a duration pair — the failure they exist for is `period_value =
--     14` with `period_unit` NULL, and `addDuration` ends
--     `const step = period.unit === 'weeks' ? 7 : 1`, so a NULL unit is silently
--     priced as DAYS. §4.1's "never fails open" would be defeated before the
--     resolver ran.
--   * An `EXCLUDE USING gist` on `fixed_due_date_ranges`. The one place in this
--     schema `btree_gist` earns the installation the baseline gave it: two date
--     ranges can overlap PARTIALLY, which a unique index cannot see.
--   * The two singleton CHECKs. `check:schema-conventions` allows an INTEGER
--     `id` only alongside an UNQUOTED `ALTER TABLE <t> … CHECK (id = 1)`, which
--     is why these are written by hand — Prisma quotes, and the gate's regex
--     does not match a quoted table name.
--   * Sixteen changelog triggers, generated by `scripts/gen-changelog-triggers.mjs`.
--   * Fourteen version-bump triggers. See the block that carries them.
--
-- NO `circulation_rules_resolve_idx`. §3 proposes
-- `(priority DESC, specificity DESC, id) WHERE enabled` and it is measured
-- harmful: at the 500-rule acceptance size on PG 16.15 the planner never chose
-- it, and forcing it read 403 buffers against 5 for a seq scan and sort, because
-- a whole-table read through a btree is random-order heap access. There is no
-- `LIMIT 1` path to serve — `resolveCirculationPolicy` takes a whole
-- `PolicySnapshot` — and `resolve.ts` re-sorts in JS, so the SQL order reaches
-- no answer. Its `id` column would only carry the ICU-el-GR-versus-UTF-16
-- divergence into a place nothing reads.
--
-- `prisma migrate deploy` does NOT wrap a migration file in a transaction, so
-- this file opens its own.

BEGIN;

SELECT pg_catalog.set_config(
  'search_path',
  pg_catalog.current_schema() || ', public',
  true
);

-- CreateEnum

-- CreateEnum
CREATE TYPE "duration_unit" AS ENUM ('minutes', 'hours', 'days', 'weeks', 'months');

-- CreateEnum
CREATE TYPE "loan_profile" AS ENUM ('rolling', 'fixed', 'indefinite');

-- CreateEnum
CREATE TYPE "closed_day_handling" AS ENUM ('keep', 'endOfPreviousOpenDay', 'startOfNextOpenDay', 'endOfNextOpenDay', 'endOfCurrentOpenHours');

-- CreateEnum
CREATE TYPE "fine_charge_at" AS ENUM ('intervalEnd', 'intervalStart');

-- CreateEnum
CREATE TYPE "renew_from" AS ENUM ('currentDueDate', 'systemDate');

-- CreateEnum
CREATE TYPE "renewal_cutoff_basis" AS ENUM ('dueDate', 'now');

-- CreateEnum
CREATE TYPE "forgive_trigger" AS ENUM ('renewal', 'claimedReturned', 'declaredLost', 'foundAfterLost');

-- CreateEnum
CREATE TYPE "lost_item_fee_basis" AS ENUM ('replacementPrice', 'itemTypeDefault', 'fixedAmount', 'actualCost');

-- CreateEnum
CREATE TYPE "hold_request_type" AS ENUM ('page', 'hold', 'recall');

-- CreateEnum
CREATE TYPE "on_shelf_holds" AS ENUM ('allow', 'deny', 'ifAnyUnavailable', 'ifAllUnavailable');

-- CreateEnum
CREATE TYPE "item_level_holds" AS ENUM ('allow', 'deny', 'force');

-- CreateEnum
CREATE TYPE "hold_pickup_policy" AS ENUM ('any', 'owningBranch', 'patronHomeBranch', 'holdingBranch', 'explicitSet');

-- CreateEnum
CREATE TYPE "notice_trigger_kind" AS ENUM ('checkout', 'checkin', 'dueSoon', 'overdue', 'holdAvailable', 'holdExpiring', 'feeCharged');

-- THE SIX STATEMENTS `migrate diff` EMITTED HERE ARE DELETED, NOT APPLIED.
--
-- `--from-config-datasource --to-schema` renders the WHOLE gap between the
-- deployed schema and the datamodel, and part of that gap is permanent: a GIN
-- trigram index, two STORED generated columns and two standalone sequences are
-- things Prisma's datamodel cannot hold, so the diff proposes dropping them on
-- every run and `scripts/check-schema-drift.ts` allowlists exactly those six
-- statements with a reason each. Applying them here would drop
-- `bib_records_search_trgm`, `fees.outstanding_cents`, `items.is_shelf_available`
-- and both sequences — measured: the file fails at
-- `cannot drop sequence marc_public_no_seq because other objects depend on it`,
-- which is the good outcome, because the two DROP COLUMNs before it would have
-- succeeded.
--
-- The rule when generating a migration in this folder: keep the CREATEs, delete
-- anything that closes pre-existing allowlisted drift, and re-run
-- `pnpm check:schema-drift` afterwards — an allowlist entry that stops matching
-- is itself a failure, so the gate proves the six are still there.

-- CreateTable
CREATE TABLE "calendars" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "name_i18n" JSONB NOT NULL DEFAULT '{}',
    "defined_from" DATE NOT NULL,
    "defined_to" DATE NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "calendars_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calendar_hours" (
    "id" TEXT NOT NULL,
    "calendar_id" TEXT NOT NULL,
    "weekday" SMALLINT NOT NULL,
    "open_min" INTEGER NOT NULL,
    "close_min" INTEGER NOT NULL,

    CONSTRAINT "calendar_hours_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calendar_exceptions" (
    "id" TEXT NOT NULL,
    "calendar_id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "name" TEXT NOT NULL,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "calendar_exceptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calendar_exception_hours" (
    "id" TEXT NOT NULL,
    "exception_id" TEXT NOT NULL,
    "open_min" INTEGER NOT NULL,
    "close_min" INTEGER NOT NULL,

    CONSTRAINT "calendar_exception_hours_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "loan_policies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "loanable" BOOLEAN NOT NULL DEFAULT true,
    "profile" "loan_profile" NOT NULL DEFAULT 'rolling',
    "period_value" INTEGER,
    "period_unit" "duration_unit",
    "fixed_due_date_set_id" TEXT,
    "due_time_of_day_min" INTEGER,
    "closed_day_handling" "closed_day_handling" NOT NULL DEFAULT 'keep',
    "opening_time_offset_value" INTEGER,
    "opening_time_offset_unit" "duration_unit",
    "max_period_value" INTEGER,
    "max_period_unit" "duration_unit",
    "renewable" BOOLEAN NOT NULL DEFAULT true,
    "renewals_allowed" INTEGER,
    "renewal_period_value" INTEGER,
    "renewal_period_unit" "duration_unit",
    "renew_from" "renew_from" NOT NULL DEFAULT 'currentDueDate',
    "no_renewal_before_value" INTEGER,
    "no_renewal_before_unit" "duration_unit",
    "no_renewal_before_relative_to" "renewal_cutoff_basis" NOT NULL DEFAULT 'dueDate',
    "renew_with_outstanding_holds" BOOLEAN NOT NULL DEFAULT true,
    "alt_checkout_period_with_holds_value" INTEGER,
    "alt_checkout_period_with_holds_unit" "duration_unit",
    "alt_renewal_period_with_holds_value" INTEGER,
    "alt_renewal_period_with_holds_unit" "duration_unit",
    "item_limit_for_policy" INTEGER,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "loan_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "overdue_fine_policies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "currency" CHAR(3) NOT NULL DEFAULT 'EUR',
    "interval_value" INTEGER NOT NULL,
    "interval_unit" "duration_unit" NOT NULL,
    "amount_per_interval_cents" BIGINT NOT NULL,
    "charge_at" "fine_charge_at" NOT NULL DEFAULT 'intervalEnd',
    "grace_period_value" INTEGER,
    "grace_period_unit" "duration_unit",
    "grace_suppresses_notice" BOOLEAN NOT NULL DEFAULT true,
    "count_closed_days" BOOLEAN NOT NULL DEFAULT true,
    "maximum_fine_cents" BIGINT,
    "minimum_fine_cents" BIGINT,
    "cap_at_replacement_cost" BOOLEAN NOT NULL DEFAULT false,
    "forgive_on" "forgive_trigger"[] DEFAULT ARRAY[]::"forgive_trigger"[],
    "suspension_days_per_overdue_day" INTEGER,
    "suspension_max_days" INTEGER,
    "suspension_reset_on_return" BOOLEAN,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "overdue_fine_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lost_item_fee_policies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "currency" CHAR(3) NOT NULL DEFAULT 'EUR',
    "charge_basis" "lost_item_fee_basis" NOT NULL DEFAULT 'replacementPrice',
    "fixed_amount_cents" BIGINT,
    "processing_fee_cents" BIGINT NOT NULL DEFAULT 0,
    "aged_to_lost_after_value" INTEGER NOT NULL,
    "aged_to_lost_after_unit" "duration_unit" NOT NULL,
    "refund_replacement_on_return" BOOLEAN NOT NULL DEFAULT true,
    "refund_processing_fee_on_return" BOOLEAN NOT NULL DEFAULT false,
    "refund_window_value" INTEGER,
    "refund_window_unit" "duration_unit",
    "stop_overdue_accrual_on_lost" BOOLEAN NOT NULL DEFAULT true,
    "charge_overdue_up_to_lost" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "lost_item_fee_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "hold_policies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "currency" CHAR(3) NOT NULL DEFAULT 'EUR',
    "holds_allowed" BOOLEAN NOT NULL DEFAULT true,
    "request_types" "hold_request_type"[] DEFAULT ARRAY['hold']::"hold_request_type"[],
    "on_shelf_holds" "on_shelf_holds" NOT NULL DEFAULT 'allow',
    "item_level_holds" "item_level_holds" NOT NULL DEFAULT 'allow',
    "max_holds_per_record" INTEGER,
    "max_holds_total" INTEGER,
    "pickup_policy" "hold_pickup_policy" NOT NULL DEFAULT 'any',
    "hold_shelf_expiry_value" INTEGER NOT NULL,
    "hold_shelf_expiry_unit" "duration_unit" NOT NULL,
    "shelf_expiry_uses_calendar" BOOLEAN NOT NULL DEFAULT true,
    "unfilled_request_expiry_value" INTEGER,
    "unfilled_request_expiry_unit" "duration_unit",
    "suspension_allowed" BOOLEAN NOT NULL DEFAULT true,
    "max_suspension_value" INTEGER,
    "max_suspension_unit" "duration_unit",
    "placement_fee_cents" BIGINT,
    "not_picked_up_fee_cents" BIGINT,
    "transit_allowed" BOOLEAN NOT NULL DEFAULT true,
    "max_transit_days" INTEGER,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "hold_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "hold_policy_pickup_branches" (
    "id" TEXT NOT NULL,
    "hold_policy_id" TEXT NOT NULL,
    "branch_id" TEXT NOT NULL,

    CONSTRAINT "hold_policy_pickup_branches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notice_policies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "notice_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notice_policy_templates" (
    "id" TEXT NOT NULL,
    "notice_policy_id" TEXT NOT NULL,
    "trigger" "notice_trigger_kind" NOT NULL,
    "template_id" TEXT NOT NULL,
    "branch_id" TEXT,
    "patron_category_id" TEXT,
    "offset_value" INTEGER,
    "offset_unit" "duration_unit",
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notice_policy_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "fixed_due_date_sets" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "fixed_due_date_sets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "fixed_due_date_ranges" (
    "id" TEXT NOT NULL,
    "set_id" TEXT NOT NULL,
    "from" DATE NOT NULL,
    "to" DATE NOT NULL,
    "due_date" DATE NOT NULL,
    "due_time_of_day_min" INTEGER,

    CONSTRAINT "fixed_due_date_ranges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "patron_categories" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "name_i18n" JSONB NOT NULL DEFAULT '{}',
    "min_age_years" INTEGER,
    "can_be_proxy" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "patron_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "patron_category_limits" (
    "patron_category_id" TEXT NOT NULL,
    "max_loans" INTEGER,
    "max_holds" INTEGER,
    "max_overdues" INTEGER,
    "currency" CHAR(3) NOT NULL DEFAULT 'EUR',
    "max_fine_balance_cents" BIGINT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "patron_category_limits_pkey" PRIMARY KEY ("patron_category_id")
);

-- CreateTable
CREATE TABLE "circulation_rules" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "patron_category_id" TEXT,
    "item_type_id" TEXT,
    "owning_branch_id" TEXT,
    "shelving_location_id" TEXT,
    "checkout_branch_id" TEXT,
    "pickup_branch_id" TEXT,
    "loan_policy_id" TEXT NOT NULL,
    "overdue_fine_policy_id" TEXT NOT NULL,
    "lost_item_fee_policy_id" TEXT NOT NULL,
    "hold_policy_id" TEXT NOT NULL,
    "notice_policy_id" TEXT NOT NULL,
    "max_loans_for_rule" INTEGER,
    "max_holds_for_rule" INTEGER,
    "age_restriction_min_years" INTEGER,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "effective_from" TIMESTAMPTZ(3),
    "effective_to" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "circulation_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "circulation_policy_version" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "version" INTEGER NOT NULL DEFAULT 1,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "circulation_policy_version_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "circulation_settings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "circulation_rules_enabled" BOOLEAN NOT NULL DEFAULT false,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "circulation_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "calendar_hours_calendar_id_weekday_idx" ON "calendar_hours"("calendar_id", "weekday");

-- CreateIndex
CREATE UNIQUE INDEX "calendar_exceptions_one_per_date" ON "calendar_exceptions"("calendar_id", "date");

-- CreateIndex
CREATE INDEX "calendar_exception_hours_exception_id_idx" ON "calendar_exception_hours"("exception_id");

-- CreateIndex
CREATE INDEX "hold_policy_pickup_branches_branch_id_idx" ON "hold_policy_pickup_branches"("branch_id");

-- CreateIndex
CREATE UNIQUE INDEX "hold_policy_pickup_branches_pair" ON "hold_policy_pickup_branches"("hold_policy_id", "branch_id");

-- CreateIndex
CREATE INDEX "notice_policy_templates_notice_policy_id_trigger_idx" ON "notice_policy_templates"("notice_policy_id", "trigger");

-- CreateIndex
CREATE INDEX "fixed_due_date_ranges_set_id_idx" ON "fixed_due_date_ranges"("set_id");

-- AddForeignKey
ALTER TABLE "branches" ADD CONSTRAINT "branches_calendar_id_fkey" FOREIGN KEY ("calendar_id") REFERENCES "calendars"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patrons" ADD CONSTRAINT "patrons_patron_category_id_fkey" FOREIGN KEY ("patron_category_id") REFERENCES "patron_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendar_hours" ADD CONSTRAINT "calendar_hours_calendar_id_fkey" FOREIGN KEY ("calendar_id") REFERENCES "calendars"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendar_exceptions" ADD CONSTRAINT "calendar_exceptions_calendar_id_fkey" FOREIGN KEY ("calendar_id") REFERENCES "calendars"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendar_exception_hours" ADD CONSTRAINT "calendar_exception_hours_exception_id_fkey" FOREIGN KEY ("exception_id") REFERENCES "calendar_exceptions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "loan_policies" ADD CONSTRAINT "loan_policies_fixed_due_date_set_id_fkey" FOREIGN KEY ("fixed_due_date_set_id") REFERENCES "fixed_due_date_sets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hold_policy_pickup_branches" ADD CONSTRAINT "hold_policy_pickup_branches_hold_policy_id_fkey" FOREIGN KEY ("hold_policy_id") REFERENCES "hold_policies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hold_policy_pickup_branches" ADD CONSTRAINT "hold_policy_pickup_branches_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notice_policy_templates" ADD CONSTRAINT "notice_policy_templates_notice_policy_id_fkey" FOREIGN KEY ("notice_policy_id") REFERENCES "notice_policies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fixed_due_date_ranges" ADD CONSTRAINT "fixed_due_date_ranges_set_id_fkey" FOREIGN KEY ("set_id") REFERENCES "fixed_due_date_sets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "patron_category_limits" ADD CONSTRAINT "patron_category_limits_patron_category_id_fkey" FOREIGN KEY ("patron_category_id") REFERENCES "patron_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "circulation_rules" ADD CONSTRAINT "circulation_rules_loan_policy_id_fkey" FOREIGN KEY ("loan_policy_id") REFERENCES "loan_policies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "circulation_rules" ADD CONSTRAINT "circulation_rules_overdue_fine_policy_id_fkey" FOREIGN KEY ("overdue_fine_policy_id") REFERENCES "overdue_fine_policies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "circulation_rules" ADD CONSTRAINT "circulation_rules_lost_item_fee_policy_id_fkey" FOREIGN KEY ("lost_item_fee_policy_id") REFERENCES "lost_item_fee_policies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "circulation_rules" ADD CONSTRAINT "circulation_rules_hold_policy_id_fkey" FOREIGN KEY ("hold_policy_id") REFERENCES "hold_policies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "circulation_rules" ADD CONSTRAINT "circulation_rules_notice_policy_id_fkey" FOREIGN KEY ("notice_policy_id") REFERENCES "notice_policies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- The generated column, and the two indexes §3 specifies
-- ---------------------------------------------------------------------------

ALTER TABLE circulation_rules
  ADD COLUMN specificity smallint GENERATED ALWAYS AS (
      (CASE WHEN patron_category_id   IS NOT NULL THEN 32 ELSE 0 END)
    + (CASE WHEN item_type_id         IS NOT NULL THEN 16 ELSE 0 END)
    + (CASE WHEN owning_branch_id     IS NOT NULL THEN  8 ELSE 0 END)
    + (CASE WHEN shelving_location_id IS NOT NULL THEN  4 ELSE 0 END)
    + (CASE WHEN checkout_branch_id   IS NOT NULL THEN  2 ELSE 0 END)
    + (CASE WHEN pickup_branch_id     IS NOT NULL THEN  1 ELSE 0 END)) STORED;

-- Two rules with the same six selectors are not a tie the resolver can break —
-- `compareRank` would fall through to the id, and which of two identical scopes
-- wins would depend on a cuid. COALESCE to '' because NULL never equals NULL in
-- a unique index, so without it the wildcard row is unconstrained and so is
-- every rule with any selector blank.
CREATE UNIQUE INDEX circulation_rules_scope_unique ON circulation_rules (
  COALESCE(patron_category_id, ''), COALESCE(item_type_id, ''),
  COALESCE(owning_branch_id, ''), COALESCE(shelving_location_id, ''),
  COALESCE(checkout_branch_id, ''), COALESCE(pickup_branch_id, ''))
  WHERE enabled AND effective_to IS NULL;

-- AT MOST ONE ENABLED WILDCARD, EVER. §3's predicate exactly — `specificity = 0
-- AND enabled` — and deliberately NOT widened with `effective_to IS NULL`.
-- Widening it would admit two enabled wildcards at once (one expiring, one not),
-- both in force today, both at priority 0 and specificity 0, and `compareRank`
-- would then decide the DEFAULT RULE of the library by comparing two cuids. The
-- narrow predicate makes that state unreachable; scheduling a new default is
-- done by editing the one row, which is also the only way it stays explicable.
CREATE UNIQUE INDEX circulation_rules_default_singleton
  ON circulation_rules ((true))
  WHERE specificity = 0 AND enabled;

-- The matrix editor lists rules to a human, and `/circulation/explain` renders
-- the neighbours a rule beat. Those orderings must agree with `compareRank`,
-- whose id tiebreak is UTF-16 code units, and the tenant collation is ICU el-GR
-- — measured to differ: `r_default < r-default` under ICU and the reverse under
-- C, and `CKV1A2B3C` sorts first under C and mid-list under ICU. Generated cuids
-- provably cannot diverge (the whole `[0-9a-z]` alphabet orders identically
-- under both), but a seeded, imported or human-chosen id can, and a UI that
-- lists rules in a different order than the engine ranks them is the same bug
-- wearing a different hat. This index is what makes `ORDER BY … id COLLATE "C"`
-- cheap for those listings.
CREATE INDEX circulation_rules_listing_idx
  ON circulation_rules (priority DESC, specificity DESC, id COLLATE "C");

-- ---------------------------------------------------------------------------
-- The duration pairs
-- ---------------------------------------------------------------------------
--
-- TWELVE nullable pairs, each with a named CHECK so the error says which field.
-- `period_value = 14` with `period_unit` NULL is the failure: `addDuration` ends
-- `const step = period.unit === 'weeks' ? 7 : 1`, so a NULL unit is priced as
-- DAYS and a two-hour reserve becomes a fortnight's loan. A composite type would
-- have made the pair atomic; Prisma maps composites to `Unsupported`, which the
-- client cannot read at all.

ALTER TABLE loan_policies
  ADD CONSTRAINT loan_policies_period_pair
    CHECK ((period_value IS NULL) = (period_unit IS NULL)),
  ADD CONSTRAINT loan_policies_opening_time_offset_pair
    CHECK ((opening_time_offset_value IS NULL) = (opening_time_offset_unit IS NULL)),
  ADD CONSTRAINT loan_policies_max_period_pair
    CHECK ((max_period_value IS NULL) = (max_period_unit IS NULL)),
  ADD CONSTRAINT loan_policies_renewal_period_pair
    CHECK ((renewal_period_value IS NULL) = (renewal_period_unit IS NULL)),
  ADD CONSTRAINT loan_policies_no_renewal_before_pair
    CHECK ((no_renewal_before_value IS NULL) = (no_renewal_before_unit IS NULL)),
  ADD CONSTRAINT loan_policies_alt_checkout_pair
    CHECK ((alt_checkout_period_with_holds_value IS NULL)
         = (alt_checkout_period_with_holds_unit IS NULL)),
  ADD CONSTRAINT loan_policies_alt_renewal_pair
    CHECK ((alt_renewal_period_with_holds_value IS NULL)
         = (alt_renewal_period_with_holds_unit IS NULL)),
  -- A duration of zero is not a duration; a negative one is a due date before
  -- the checkout. `openingTimeOffset` is the exception — an offset of zero is
  -- "open the loan at opening time", which is meaningful.
  ADD CONSTRAINT loan_policies_durations_positive CHECK (
        (period_value IS NULL OR period_value > 0)
    AND (max_period_value IS NULL OR max_period_value > 0)
    AND (renewal_period_value IS NULL OR renewal_period_value > 0)
    AND (no_renewal_before_value IS NULL OR no_renewal_before_value > 0)
    AND (alt_checkout_period_with_holds_value IS NULL
         OR alt_checkout_period_with_holds_value > 0)
    AND (alt_renewal_period_with_holds_value IS NULL
         OR alt_renewal_period_with_holds_value > 0)
    AND (opening_time_offset_value IS NULL OR opening_time_offset_value >= 0)),
  ADD CONSTRAINT loan_policies_renewals_allowed_non_negative
    CHECK (renewals_allowed IS NULL OR renewals_allowed >= 0),
  ADD CONSTRAINT loan_policies_item_limit_positive
    CHECK (item_limit_for_policy IS NULL OR item_limit_for_policy > 0),
  ADD CONSTRAINT loan_policies_due_time_of_day_range
    CHECK (due_time_of_day_min IS NULL
           OR (due_time_of_day_min >= 0 AND due_time_of_day_min < 1440)),
  -- A `fixed` profile with no set resolves to `NO_FIXED_DUE_DATE_RANGE` on every
  -- checkout; a `rolling` one with no period silently becomes zero. Both are
  -- refused here, where the librarian is looking at the form.
  ADD CONSTRAINT loan_policies_profile_complete CHECK (
    CASE profile
      WHEN 'rolling'    THEN period_value IS NOT NULL AND fixed_due_date_set_id IS NULL
      WHEN 'fixed'      THEN fixed_due_date_set_id IS NOT NULL AND period_value IS NULL
      WHEN 'indefinite' THEN period_value IS NULL AND fixed_due_date_set_id IS NULL
    END);

ALTER TABLE overdue_fine_policies
  ADD CONSTRAINT overdue_fine_policies_grace_period_pair
    CHECK ((grace_period_value IS NULL) = (grace_period_unit IS NULL)),
  ADD CONSTRAINT overdue_fine_policies_durations_positive CHECK (
        interval_value > 0
    AND (grace_period_value IS NULL OR grace_period_value > 0)),
  ADD CONSTRAINT overdue_fine_policies_amounts_non_negative CHECK (
        amount_per_interval_cents >= 0
    AND (maximum_fine_cents IS NULL OR maximum_fine_cents >= 0)
    AND (minimum_fine_cents IS NULL OR minimum_fine_cents >= 0)),
  -- A minimum above the maximum makes every fine both, and `accrueOverdue`
  -- applies them in an order that would then decide the answer.
  ADD CONSTRAINT overdue_fine_policies_min_below_max CHECK (
    minimum_fine_cents IS NULL OR maximum_fine_cents IS NULL
    OR minimum_fine_cents <= maximum_fine_cents),
  -- All three or none. A half-written suspension policy inserts cleanly and then
  -- suspends a patron for `undefined` days.
  ADD CONSTRAINT overdue_fine_policies_suspension_complete CHECK (
    (suspension_days_per_overdue_day IS NULL AND suspension_reset_on_return IS NULL
       AND suspension_max_days IS NULL)
    OR (suspension_days_per_overdue_day IS NOT NULL AND suspension_reset_on_return IS NOT NULL)),
  ADD CONSTRAINT overdue_fine_policies_suspension_positive CHECK (
        (suspension_days_per_overdue_day IS NULL OR suspension_days_per_overdue_day > 0)
    AND (suspension_max_days IS NULL OR suspension_max_days > 0));

ALTER TABLE lost_item_fee_policies
  ADD CONSTRAINT lost_item_fee_policies_refund_window_pair
    CHECK ((refund_window_value IS NULL) = (refund_window_unit IS NULL)),
  ADD CONSTRAINT lost_item_fee_policies_durations_positive CHECK (
        aged_to_lost_after_value > 0
    AND (refund_window_value IS NULL OR refund_window_value > 0)),
  ADD CONSTRAINT lost_item_fee_policies_amounts_non_negative CHECK (
        processing_fee_cents >= 0
    AND (fixed_amount_cents IS NULL OR fixed_amount_cents >= 0)),
  -- `fixedAmount` with no amount charges nothing and looks configured.
  ADD CONSTRAINT lost_item_fee_policies_fixed_amount_present
    CHECK (charge_basis <> 'fixedAmount' OR fixed_amount_cents IS NOT NULL);

ALTER TABLE hold_policies
  ADD CONSTRAINT hold_policies_unfilled_expiry_pair
    CHECK ((unfilled_request_expiry_value IS NULL) = (unfilled_request_expiry_unit IS NULL)),
  ADD CONSTRAINT hold_policies_max_suspension_pair
    CHECK ((max_suspension_value IS NULL) = (max_suspension_unit IS NULL)),
  ADD CONSTRAINT hold_policies_durations_positive CHECK (
        hold_shelf_expiry_value > 0
    AND (unfilled_request_expiry_value IS NULL OR unfilled_request_expiry_value > 0)
    AND (max_suspension_value IS NULL OR max_suspension_value > 0)
    AND (max_transit_days IS NULL OR max_transit_days > 0)),
  ADD CONSTRAINT hold_policies_amounts_non_negative CHECK (
        (placement_fee_cents IS NULL OR placement_fee_cents >= 0)
    AND (not_picked_up_fee_cents IS NULL OR not_picked_up_fee_cents >= 0)),
  ADD CONSTRAINT hold_policies_max_holds_positive CHECK (
        (max_holds_per_record IS NULL OR max_holds_per_record > 0)
    AND (max_holds_total IS NULL OR max_holds_total > 0)),
  -- An empty `request_types` on a policy that allows holds is a policy under
  -- which nothing can be requested — configured, and inert.
  ADD CONSTRAINT hold_policies_request_types_present
    CHECK (NOT holds_allowed OR pg_catalog.array_length(request_types, 1) >= 1);

ALTER TABLE notice_policy_templates
  ADD CONSTRAINT notice_policy_templates_offset_pair
    CHECK ((offset_value IS NULL) = (offset_unit IS NULL)),
  ADD CONSTRAINT notice_policy_templates_offset_positive
    CHECK (offset_value IS NULL OR offset_value > 0);

ALTER TABLE patron_category_limits
  ADD CONSTRAINT patron_category_limits_non_negative CHECK (
        (max_loans IS NULL OR max_loans >= 0)
    AND (max_holds IS NULL OR max_holds >= 0)
    AND (max_overdues IS NULL OR max_overdues >= 0)
    AND (max_fine_balance_cents IS NULL OR max_fine_balance_cents >= 0));

ALTER TABLE circulation_rules
  ADD CONSTRAINT circulation_rules_limits_non_negative CHECK (
        (max_loans_for_rule IS NULL OR max_loans_for_rule >= 0)
    AND (max_holds_for_rule IS NULL OR max_holds_for_rule >= 0)
    AND (age_restriction_min_years IS NULL OR age_restriction_min_years >= 0)),
  -- A window that closes before it opens matches nothing, and `isInForce` cannot
  -- tell that from a rule deliberately scheduled for later.
  ADD CONSTRAINT circulation_rules_effective_window
    CHECK (effective_from IS NULL OR effective_to IS NULL OR effective_from < effective_to);

ALTER TABLE patron_categories
  ADD CONSTRAINT patron_categories_min_age_sane
    CHECK (min_age_years IS NULL OR (min_age_years >= 0 AND min_age_years < 130));

-- ---------------------------------------------------------------------------
-- The calendar
-- ---------------------------------------------------------------------------

ALTER TABLE calendars
  -- A calendar defined backwards answers for no date at all, and the resolver's
  -- refusal would name a range that reads like a typo because it is one.
  ADD CONSTRAINT calendars_defined_range CHECK (defined_from <= defined_to);

ALTER TABLE calendar_hours
  ADD CONSTRAINT calendar_hours_weekday_range CHECK (weekday >= 0 AND weekday <= 6),
  -- `close_min` may exceed 1440 for a desk that shuts after midnight; `open_min`
  -- may not, because an interval that starts tomorrow belongs to tomorrow. The
  -- ceiling of 2880 is two days: anything beyond it is a data-entry error, not a
  -- late night.
  ADD CONSTRAINT calendar_hours_minute_range CHECK (
    open_min >= 0 AND open_min < 1440 AND close_min > open_min AND close_min <= 2880);

ALTER TABLE calendar_exception_hours
  ADD CONSTRAINT calendar_exception_hours_minute_range CHECK (
    open_min >= 0 AND open_min < 1440 AND close_min > open_min AND close_min <= 2880);

-- OVERLAPPING OPENING INTERVALS ARE REFUSED, per weekday and per exception date.
-- `hoursOn` returns the intervals in stored order and `isOpenAt` takes the first
-- that contains the minute, so 08:00–14:00 overlapping 13:00–21:00 gives an
-- "open until" that depends on row order. `btree_gist` is what lets an integer
-- equality (`calendar_id`, `weekday`) sit in the same EXCLUDE as a range
-- overlap, and the baseline installed it saying so.
ALTER TABLE calendar_hours
  ADD CONSTRAINT calendar_hours_no_overlap
  EXCLUDE USING gist (
    calendar_id WITH =,
    weekday WITH =,
    int4range(open_min, close_min) WITH &&);

ALTER TABLE calendar_exception_hours
  ADD CONSTRAINT calendar_exception_hours_no_overlap
  EXCLUDE USING gist (
    exception_id WITH =,
    int4range(open_min, close_min) WITH &&);

-- ---------------------------------------------------------------------------
-- Fixed due dates
-- ---------------------------------------------------------------------------

ALTER TABLE fixed_due_date_ranges
  ADD CONSTRAINT fixed_due_date_ranges_range CHECK ("from" <= "to"),
  -- A due date before the range it serves is a loan that is overdue at checkout.
  ADD CONSTRAINT fixed_due_date_ranges_due_after_from CHECK (due_date >= "from"),
  ADD CONSTRAINT fixed_due_date_ranges_time_range
    CHECK (due_time_of_day_min IS NULL
           OR (due_time_of_day_min >= 0 AND due_time_of_day_min < 1440)),
  -- THE ONE PLACE btree_gist EARNS ITS INSTALLATION for a genuine overlap. Two
  -- term ranges can overlap PARTIALLY — 15 Sep–20 Jan and 10 Jan–15 Jun — which
  -- a unique index cannot see, and `computeDueDate` takes the FIRST covering
  -- range, so an overlap makes the answer depend on row order. `'[]'` because
  -- both bounds are inclusive, which is what `FixedDueDateRange` says.
  ADD CONSTRAINT fixed_due_date_ranges_no_overlap
  EXCLUDE USING gist (
    set_id WITH =,
    daterange("from", "to", '[]') WITH &&);

-- ---------------------------------------------------------------------------
-- The two singletons
-- ---------------------------------------------------------------------------
--
-- UNQUOTED, deliberately. `check:schema-conventions` allows an INTEGER `id` only
-- when it finds `ALTER TABLE <table> … CHECK ( id = 1 )` unquoted within 400
-- characters, and Prisma always quotes — so a generated statement would be
-- invisible to the gate and the table would fail rule 4.

ALTER TABLE circulation_policy_version
  ADD CONSTRAINT circulation_policy_version_singleton CHECK (id = 1),
  -- The counter only ever goes up. A decrement would make every pod believe its
  -- cache is current.
  ADD CONSTRAINT circulation_policy_version_positive CHECK (version >= 1);

ALTER TABLE circulation_settings
  ADD CONSTRAINT circulation_settings_singleton CHECK (id = 1);

-- Both rows are created HERE rather than by a seed script, and that is the
-- difference between a tenant that works and one that refuses to lend.
-- `PolicySnapshotService` treats a missing counter row as a REFUSAL by name —
-- not as version 0 — because 0 never changes, so a library whose counter row was
-- gone would run forever on a snapshot no bump could ever invalidate, on every
-- pod, and nobody would find out. Creating it in the migration makes the state
-- unreachable for every tenant, including the ones phase 19's PL/pgSQL
-- copy-forward creates without touching the application.
INSERT INTO circulation_policy_version (id, version, updated_at)
  VALUES (1, 1, pg_catalog.now());
INSERT INTO circulation_settings (id, circulation_rules_enabled, updated_at)
  VALUES (1, false, pg_catalog.now());

-- ---------------------------------------------------------------------------
-- The version bump
-- ---------------------------------------------------------------------------
--
-- §4.1: the snapshot is "versioned by the trigger-maintained
-- `circulation_policy_version` counter", and trigger-maintained is the whole
-- design. §4.2 makes the argument for the changelog — "a forgotten `emit()`
-- silently breaks replicas and the index forever; a trigger is unforgettable" —
-- and here it is sharper. A forgotten bump does not break a replica: every pod
-- keeps its cached snapshot, the 30-second backstop re-reads the counter, sees
-- no change, and keeps the stale cache. Not for thirty seconds. FOREVER. The
-- librarian edits the loan period, the screen says saved, and every checkout
-- that week is priced by the old one.
--
-- The surface is also larger than the changelog's, not smaller: this phase's
-- service, the simple-mode façade, a phase-30 copy-cataloguing importer, phase
-- 19's copy-forward (PL/pgSQL, which never touches the application at all), a
-- seed script, and a support engineer in `psql`. Seventeen triggers cover all
-- six.
--
-- FOR EACH STATEMENT, NOT FOR EACH ROW. Measured on PG 16.15: a 40-row UPDATE
-- fires a row trigger 40 times and a statement trigger once. Forty `UPDATE`s of
-- the same counter row inside one transaction is 40 dead tuples and 40× the WAL
-- for one librarian's edit, and it would count ROWS TOUCHED rather than POLICY
-- STATES.
--
-- A STATEMENT TRIGGER FIRES ON ZERO AFFECTED ROWS — measured — so
-- `UPDATE circulation_rules SET enabled = true WHERE id = 'typo'` bumps the
-- version. That is over-invalidation, and it is free to accept because the
-- correctness requirement is one-directional: a different policy state MUST get
-- a different version (or a receipt cannot be reproduced and a pod's
-- revalidation misses a change), while a different version need NOT mean a
-- different state (a spurious bump costs one snapshot rebuild). The alternative
-- — a transition table with `IF EXISTS (SELECT 1 FROM new_rows)` — cannot be
-- combined with multiple events, so seventeen triggers would become fifty-one.
--
-- `OR TRUNCATE` IS IN EVERY ONE, and it matters more here than for the
-- changelog. Measured: `TRUNCATE circulation_rules` on 40 rows emits ZERO change
-- events, because the changelog is row-level and cannot see a truncate. Without
-- `OR TRUNCATE` here the version would not move either, and every pod would
-- serve the deleted matrix for ever — fully populated and completely wrong. With
-- it, every pod rebuilds, the resolver raises `NO_MATCHING_RULE`, and the desk
-- refuses to lend. Refusing is correct.
--
-- `version = version + 1` NEEDS NO LOCK OF OURS. Measured: two concurrent bumps
-- from 1 give 3, not 2 — Postgres's ReadCommitted UPDATE re-check re-fetches the
-- newly committed row and re-evaluates the expression against it, the same
-- mechanism that makes `SET balance = balance + 100` safe. A read-then-write in
-- application code, which is what bumping in a service would be, is what loses
-- the update.

CREATE OR REPLACE FUNCTION lbr2_bump_policy_version() RETURNS trigger
LANGUAGE plpgsql AS $lbr2_bump_policy_version$
BEGIN
  -- Unqualified on purpose, resolved through the search_path the caller is
  -- already in — the same reason `lbr2_write_change_event` refuses to pin its
  -- own path: `ALTER FUNCTION … SET search_path = lbr2` stores the schema name
  -- as TEXT, and after phase 20's rename that name does not exist.
  EXECUTE pg_catalog.format(
    'UPDATE %I.circulation_policy_version SET version = version + 1, updated_at = pg_catalog.now() WHERE id = 1',
    TG_TABLE_SCHEMA);
  RETURN NULL;
END;
$lbr2_bump_policy_version$;

CREATE TRIGGER calendars_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON calendars
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER calendar_hours_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON calendar_hours
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER calendar_exceptions_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON calendar_exceptions
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER calendar_exception_hours_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON calendar_exception_hours
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER loan_policies_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON loan_policies
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER overdue_fine_policies_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON overdue_fine_policies
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER lost_item_fee_policies_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON lost_item_fee_policies
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER hold_policies_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON hold_policies
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER hold_policy_pickup_branches_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON hold_policy_pickup_branches
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER notice_policies_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON notice_policies
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER notice_policy_templates_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON notice_policy_templates
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER fixed_due_date_sets_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON fixed_due_date_sets
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER fixed_due_date_ranges_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON fixed_due_date_ranges
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER patron_categories_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON patron_categories
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER patron_category_limits_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON patron_category_limits
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
CREATE TRIGGER circulation_rules_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON circulation_rules
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();
-- `circulation_settings` bumps too: `circulation_rules_enabled` travels IN the
-- snapshot, so a pod that did not rebuild would keep offering the matrix editor
-- to a library that has just turned it off.
CREATE TRIGGER circulation_settings_bump_policy_version
  AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON circulation_settings
  FOR EACH STATEMENT EXECUTE FUNCTION lbr2_bump_policy_version();

-- ---------------------------------------------------------------------------
-- The changelog triggers
-- ---------------------------------------------------------------------------
--
-- Generated by `node scripts/gen-changelog-triggers.mjs`. ONLY THE NEW TRIGGERS
-- are here; the function and the nine existing triggers are untouched.
--
-- ALL SIXTEEN NEW TABLES ARE `@replicated`, and the decisive argument is phase
-- 77 rather than a preference. `PolicySnapshot` is a CLOSED value — version,
-- rules, five policy tables, fixed due dates, category limits, calendars — and
-- every one of its fields maps onto a table here with nothing left over. A
-- device missing any one of them does not lend with a slightly wrong due date:
-- §4.1 forbids failing open, so it raises `POLICY_NOT_IN_SNAPSHOT` or
-- `CALENDAR_NOT_DEFINED_FOR` and refuses to lend. Replication here is not an
-- optimisation, it is whether the offline client functions at all.
--
-- Every clause of the `fees` exclusion inverts. `fees` is out because "the
-- overdue-fine sweep touches every accruing fee every night, so a trigger here
-- would be the single largest producer in the feed — and no consumer reads it
-- yet". These tables are written by a librarian in an admin screen; the whole
-- set changes less in a year than `fees` changes in a minute. Consumers exist
-- today: device sync and the phase-77 core need all of them, and the OPAC needs
-- `hold_policies` (`on_shelf_holds` decides whether the "Place hold" button
-- renders at all), `loan_policies` and `calendars` for its "due back" and "open
-- until" strings. And the asymmetry reverses: `fees` says "turning a firehose
-- off after a fleet has consumed it is the expensive direction", whereas here
-- the expensive direction is a fleet shipped WITHOUT policy replication, which
-- cannot resolve offline and needs a fleet-wide re-seed rather than a one-line
-- migration.
--
-- EVERY ONE IS `branch = false`, INCLUDING `circulation_rules`, and that is a
-- requirement rather than a shortcut. A rule has THREE branch columns
-- (`owning`, `checkout`, `pickup`) and no single owning branch. Setting
-- `change_events.branch_id` from `owning_branch_id` would look tidy and would
-- break floating collections and ILL: a device at branch B checking out an item
-- OWNED by branch A must match the rule scoped `owning_branch_id = 'A'`, and a
-- branch-filtered consumer (`branch_id IS NULL OR branch_id = ANY($2)`) would
-- never receive it. NULL makes every rule reach every device, which is what
-- wildcard semantics need. `notice_policy_templates.branch_id` is the same
-- shape and gets the same answer for the same reason.
--
-- `circulation_policy_version` and `circulation_settings` are NOT replicated,
-- deliberately. The counter is bumped by every one of the seventeen triggers
-- above, so replicating it would emit a change event for every policy edit
-- twice — once for the row that changed and once for the counter — and the
-- device reads the version from the sync feed's own watermark, not from a row.
-- `circulation_settings` gates a WRITE surface that does not exist on a device.
--
-- To change the set: edit the marker on the model, re-run the generator, and
-- write a NEW migration. Editing this block by hand is what the gate catches.

CREATE TRIGGER calendars_changelog
  AFTER INSERT OR UPDATE OR DELETE ON calendars
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('calendar', 'id', false);

CREATE TRIGGER calendar_hours_changelog
  AFTER INSERT OR UPDATE OR DELETE ON calendar_hours
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('calendar_hour', 'id', false);

CREATE TRIGGER calendar_exceptions_changelog
  AFTER INSERT OR UPDATE OR DELETE ON calendar_exceptions
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('calendar_exception', 'id', false);

CREATE TRIGGER calendar_exception_hours_changelog
  AFTER INSERT OR UPDATE OR DELETE ON calendar_exception_hours
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('calendar_exception_hour', 'id', false);

CREATE TRIGGER loan_policies_changelog
  AFTER INSERT OR UPDATE OR DELETE ON loan_policies
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('loan_policy', 'id', false);

CREATE TRIGGER overdue_fine_policies_changelog
  AFTER INSERT OR UPDATE OR DELETE ON overdue_fine_policies
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('overdue_fine_policy', 'id', false);

CREATE TRIGGER lost_item_fee_policies_changelog
  AFTER INSERT OR UPDATE OR DELETE ON lost_item_fee_policies
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('lost_item_fee_policy', 'id', false);

CREATE TRIGGER hold_policies_changelog
  AFTER INSERT OR UPDATE OR DELETE ON hold_policies
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('hold_policy', 'id', false);

CREATE TRIGGER hold_policy_pickup_branches_changelog
  AFTER INSERT OR UPDATE OR DELETE ON hold_policy_pickup_branches
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('hold_policy_pickup_branch', 'id', true);

CREATE TRIGGER notice_policies_changelog
  AFTER INSERT OR UPDATE OR DELETE ON notice_policies
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('notice_policy', 'id', false);

CREATE TRIGGER notice_policy_templates_changelog
  AFTER INSERT OR UPDATE OR DELETE ON notice_policy_templates
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('notice_policy_template', 'id', true);

CREATE TRIGGER fixed_due_date_sets_changelog
  AFTER INSERT OR UPDATE OR DELETE ON fixed_due_date_sets
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('fixed_due_date_set', 'id', false);

CREATE TRIGGER fixed_due_date_ranges_changelog
  AFTER INSERT OR UPDATE OR DELETE ON fixed_due_date_ranges
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('fixed_due_date_range', 'id', false);

CREATE TRIGGER patron_categories_changelog
  AFTER INSERT OR UPDATE OR DELETE ON patron_categories
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('patron_category', 'id', false);

CREATE TRIGGER patron_category_limits_changelog
  AFTER INSERT OR UPDATE OR DELETE ON patron_category_limits
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('patron_category_limit', 'patron_category_id', false);

CREATE TRIGGER circulation_rules_changelog
  AFTER INSERT OR UPDATE OR DELETE ON circulation_rules
  FOR EACH ROW EXECUTE FUNCTION lbr2_write_change_event('circulation_rule', 'id', false);

COMMIT;
